### ISSUE TITLE
Consider adding DateInterval.Intersection/Union etc

### ISSUE THREAD

**Issue by carlosschults** [nodatime/nodatime#1037]
In the same spirit of #977, maybe it would make sense to add methods such as the following to the `DateInterval` type:

- `bool Contains(DateInterval other)`
- `bool Intersects(DateInterval other)`
- `DateInterval? Intersection(DateInterval other)`
- `DateInterval Union(DateInterval other)`

**Comment by jskeet** [comment]
Possibly - it should be simpler as DateInterval can't be infinite.

**Comment by carlosschults** [comment]
Nice. Can I give it a try?

**Comment by jskeet** [comment]
Absolutely, but it might be worth waiting until all the decisions for #977 have been taken - unless you think none of the open questions there apply to DateInterval, which is entirely feasible.

**Comment by carlosschults** [comment]
> Absolutely, but it might be worth waiting until all the decisions for #977 have been taken - unless you think none of the open questions there apply to DateInterval, which is entirely feasible.

I'm not sure if the questions there  really apply here. I mean, there is no such a thing as an empty `DateInterval`, right?

> (Perhaps Union should return DateInterval? too? Otherwise non-overlapping date intervals could create problems.)

Got it.

**Comment by jskeet** [comment]
Yup, it's entirely possible that none of the corner cases apply here. Implement away :)

(One thing to be careful of is different calendar systems, though. That will bring a whole different set of issues.)

**Comment by malcolmr** [comment]
> I'm not sure if the questions there really apply here. I mean, there is no such a thing as an empty `DateInterval`, right?

Correct (and as Jon mentions, they're bounded), so I don't think #977 applies. I think there are still a few things to be worked out though:

- Would something like "subset-of" be a better description that "contains", for the relationship between two intervals? We already have `DateInterval.Contains(LocalDate)`; is `Contains(DateInterval)` sufficiently similar that an overload makes sense, or should we have a different method name? ("Subset" itself is also potentially confusing because it may be interpreted as "proper subset".)
- Should the union of two disjoint intervals return `DateInterval?` (as Jon suggests), or should it throw an exception?
- Do we need another method to return the smallest interval covering two (possibly-disjoint) intervals, or is that unlikely to be useful?
- What should the union of two abutting intervals be? It's reasonable to say that [Monday, Wednesday] + [Saturday, Sunday] is ill-formed, and [Monday, Saturday] + [Saturday, Sunday] is [Monday, Sunday], but what about [Monday, Friday] + [Saturday, Sunday]? Since the intervals here are closed intervals, I think it could be reasonable to consider such a union as well-formed, but it does make it harder to describe what `Union` would return.
- Related to which, do we need an 'Abuts' method to detect the above?

(I assume that `Intersects(DateInterval)` ⇔ `Intersection(DateInterval) != null`, even we don't actually implement it like that.)

**Comment by carlosschults** [comment]
> (One thing to be careful of is different calendar systems, though. That will bring a whole different set of issues.)

I'm checking and throwing when the parameter is in another Calendar. Does that make sense?

**Comment by jskeet** [comment]
> I'm checking and throwing when the parameter is in another Calendar. Does that make sense?

Yup, absolutely. It's fairly easy to detect if you're in the rare situation where you *might* get into trouble, so it's fine to throw.

I'm not so sure about throwing from Union, as that requires some slightly-hard-to-get-right logic to check beforehand. Regarding Malcolm's other question about the union of abutting intervals - I'd definitely make [Monday, Friday] + [Saturday, Sunday] = [Monday, Sunday]. It's a single interval that contains the union of all the dates contained in the original intervals.

**Comment by carlosschults** [comment]
> Would something like "subset-of" be a better description that "contains", for the relationship between two intervals? We already have DateInterval.Contains(LocalDate); is Contains(DateInterval) sufficiently similar that an overload makes sense, or should we have a different method name? ("Subset" itself is also potentially confusing because it may be interpreted as "proper subset".)

I think there is also potential for confusion even if we go with `Contains`. I thought of implementing it in such a way that two equal intervals both contain  each other. I think that would make more sense *mathematically*, but maybe it'd be somewhat non-intuitive in regards to the way people use the verb Contain in  coloquial English (I'm not a native speaker, so my interpretation here might be wrong). So, I think it's a trade-off.

> Should the union of two disjoint intervals return DateInterval? (as Jon suggests), or should it throw an exception?

I don't think a have a strong argument for either side.

> Do we need another method to return the smallest interval covering two (possibly-disjoint) intervals, or is that unlikely to be useful?

Not sure if I understand. Something like [Monday..Wednesday] + [Friday..Saturday] = [Monday..Saturday]?

> What should the union of two abutting intervals be? It's reasonable to say that [Monday, Wednesday] + [Saturday, Sunday] is ill-formed, and [Monday, Saturday] + [Saturday, Sunday] is [Monday, Sunday], but what about [Monday, Friday] + [Saturday, Sunday]? Since the intervals here are closed intervals, I think it could be reasonable to consider such a union as well-formed, but it does make it harder to describe what Union would return.

I think it makes perfect sense to return [Monday..Sunday] in this case.

> Related to which, do we need an 'Abuts' method to detect the above?

I think so, yes, if we go with the above.

**Comment by malcolmr** [comment]
I think `Contains(DateInterval)` probably will end up in a situation where `di1.Equals(di2)` ⇔ `di1.Contains(di2) && di2.Contains(di1)`, won't it? (As well as `di.Contains(di) == true`.)

Since we already have `Contains(LocalDate)` that allows a `DateInterval` of a single day to 'contain' a date of that day, I think it _is_ probably reasonable to add a `DateInterval`-accepting overload.

> Not sure if I understand. Something like [Monday..Wednesday] + [Friday..Saturday] = [Monday..Saturday]?

Exactly, yes. I'm not sure if it's that useful, though.

I don't have strong arguments for much of the rest either; I'd just like us to make decisions deliberately rather than accidentally :)

**Comment by carlosschults** [comment]
@jskeet I'd like to tackle `Union` now. Could you please elaborate on the difficulties of detecting the invalid calendars that you've mentioned before?

@malcolmr What do you think about something like this:

```csharp
public DateInterval Union (DateInterval interval, bool allowDisjointedIntervals = false)
```
Worth it?

**Comment by jskeet** [comment]
You've already done the work for detecting different calendars - that's fine.

I wouldn't bother with "allowDisjointedIntervals" - just allow abutting intervals to be "unioned". Return null if the intervals are *completely* disjoint (i.e. there's a gap between one and the other).

**Comment by malcolmr** [comment]
(+1)
