### ISSUE TITLE
Explicitly provide netstandard2.0 binaries

### ISSUE THREAD

**Issue by damageboy** [nodatime/nodatime#1053]
I understand this might sound like an odd request to say the least, but I'm encountering an extremely annoying issue when trying to restore my own project(s) which are dependent on both external ns1.x and  netstandard2.0 nuget packages... (for example dapper + nodatime).

Here are a couple of previous issues reporting similar errors with other nugets:
https://github.com/dotnet/core/issues/907
https://github.com/dotnet/sdk/issues/1792

Here's a sample repro repo from the last issue:
https://github.com/ogreenz/rid-netstandard2-repro

Basically, the gist of this is that nugets that require a netstandard1.x dependency while a netstandard2.0 dependency is also required are "forcing" a downgrade of the stdlib nugets like for example `System.IO.FileSystem.Primitives` 

The only solution I could find is to forcefully request a version >= 4.3.0 in my OWN project or face the cryptic `NU1605` warning which is treated by default as an error since sometime during the netcore 2.0.0 preview period...

It would be great if users are not forced to individually deal with this cryptic error by providing a ns2.0 binary as part of the NodaTime nugets.

**Comment by jskeet** [comment]
This feels like it's something that should be solved by Microsoft centrally rather than *every single NuGet package targeting netstandard1.x* having to also provide netstandard2.0. I would be reluctant to introduce a netstandard2.0 build to work around tooling failures that are later resolved - we'd be stuck with building three targets forever.

If a good reason is given why a netstandard1.x target can't be used properly from netstandard2.x/netcore2.x and why the right solution is to add extra targets, that's one thing - but at the moment it feels like this would just be a workaround which adds extra requirements to a huge number of package owners.

**Comment by damageboy** [comment]
I completely understand you position.
I'll close the issue.
