### ISSUE TITLE
Daylight saving issue for Europe/London

### ISSUE THREAD

**Issue by dileepkumars1** [nodatime/nodatime#1057]
Hi,

I have an issue with the UTC conversion logic for Europe/London timezone. Our application is operated by users in Europe/London timezone and the data saved in the database is in UTC. The issue is with the time between 25/03/2018 01:00 to 01:59.

The issue is when the user is selecting the time range between 01:00 and 01:59, as the DST starts at 01:00, I am expecting 00:00 (UTC) and 00:59 (UTC) respectively, so that the time will be shown correct after it is saved.  I know there are some logical problems for this as we cannot detect the actual 00:00 UTC and the 01:00 saved as 00:00.

Is there any workaround for tackling this? It would be very much helpful if there is a solution for this.

The code used is copied below.

            TimeZoneData zoneData = TimeZoneProvider.GetZone("Europe/London");
            // timer1.Start();
            DateTime startTimeBeforeDST = new DateTime(2018, 3, 25, 0, 55, 0, DateTimeKind.Local);
            DateTime startTimeInDST = new DateTime(2018, 3, 25, 1, 55, 0, DateTimeKind.Local);

            // Returned value is 3/25/2018 12:55:00 AM
            var outputBeforeDST = TimeZoneProvider.ConvertToUtc(zoneData, startTimeBeforeDST);

            // Returned value is 3/25/2018 1:55:00 AM. 
            // Here as the DST started on 01:00, the correct UTC I am expecting is 00:55 (UTC)
            // But there will be an ambiguity between the actual 00:55 and the 00:55 with UTC
            var outputInDST = TimeZoneProvider.ConvertToUtc(zoneData, startTimeInDST); 

            // Code in ConvertToUtc method.
            DateTimeZone zone = provider.GetZoneOrNull(timeZone.Name);
            return LocalDateTime.FromDateTime(dateTime).InZoneLeniently(zone).ToDateTimeUtc();

Thanks,
Dileep

**Comment by jskeet** [comment]
> The issue is when the user is selecting the time range between 01:00 and 01:59, as the DST starts at 01:00, I am expecting 00:00 (UTC) and 00:59 (UTC) respectively, so that the time will be shown correct after it is saved. 

It's not clear what you mean by "shown correct". There *is* no UTC instant that corresponds to (say) 2018-03-25T01:30:00 local time in London, because that time is skipped. It would be better to prevent your users from entering invalid times.

In the autumn when the clocks go back, *that's* when there's ambiguity - and at that point, if you need to distinguish between "1:30am the first time" and "1:30am the second time" you'll need to ask your users about it.

**Comment by jskeet** [comment]
Closing as I don't believe there's anything wrong, and the reporter hasn't provided any more comments.

**Comment by denyss-digiterre** [comment]
@jskeet 

> In the autumn when the clocks go back, _that's_ when there's ambiguity - and at that point, if you need to distinguish between "1:30am the first time" and "1:30am the second time" you'll need to ask your users about it.

Could you please clarify, is there a built-in way of handling this ambiguity in a controlled manner?

I have a source of data where date-time strings are annotated with a flag (a reserved character) to disambiguate two times during daylight savings transition. I parse them to ```LocalDateTime```.
My current approach is to also extract the flag and then carry it until I do the ```LocalDateTime``` -> ```ZonedDateTime``` transition. At that point I will pass in a resolver based on a custom ```AmbiguousTimeResolver``` resolver that will do ```(earlier, later) => flag ?  earlier : later``` resolution.

Is this a correct approach or there is something built-in to use instead? Thank you!

**Comment by jskeet** [comment]
> Could you please clarify, is there a built-in way of handling this ambiguity in a controlled manner?

Yes, when you convert from a `LocalDateTime` to a `ZonedDateTime`, you have to specify how you handle that ambiguity. It sounds like you've already spotted that and are doing basically the right thing. The only thing I'd possibly suggest is that instead of using a lambda expression, you build two resolvers beforehand, one using `Resolvers.ReturnEarlier` and one using `Resolvers.ReturnLater`. You can the use `flag ? earlierResolver : laterResolver` to avoid creating a new delegate on each conversion.

**Comment by denyss-digiterre** [comment]
@jskeet thank you very-very much!
