### ISSUE TITLE
.net standard support for xamarin.forms?

### ISSUE THREAD

**Issue by swapnil591** [nodatime/nodatime#1083]

**Comment by jskeet** [comment]
Please provide significantly more information. We support netstandard 1.3; if Xamarin.Forms can use that, that's great - otherwise I doubt that we'll be able to support it. (Note that I'm strongly considering moving to netstandard2.0 for Noda Time 3.0.)

If you're asking for Xamarin.Forms controls etc, that's a different matter.

If you can provide more details about what you're asking for, we can discuss it further - without more details, I'll just have to close this.

**Comment by jskeet** [comment]
Closing due to lack of further information.
