### ISSUE TITLE
Support for Hindu calendars

### ISSUE THREAD

**Issue by srivatsahg** [nodatime/nodatime#1097]
I see there is a support for Persian and Islamic calendars, however, I do not see the support for Hindu calendar which itself and unique and quite accurate as it looks from Moon's point of view. 

For brief information on Hindu calendar, Kindly refer the following link
https://www.timeanddate.com/calendar/hindu-calendar.html

Thanks

**Comment by jskeet** [comment]
It sounds like we'd need to work out *which* Hindu calendar or calendars we want to support - and then work out an implementation.

Assuming the Hindu calendars fit in reasonably with the expected Noda Time structure (years/months/days) it should all be doable, but it would be nice to know what would be most useful before spending time implementing them.

**Comment by jskeet** [comment]
Any more information about which Hindu calendars would be more useful? (This is the first feature request I think we've had for Hindu calendar systems, so unless I can get more information, I'm likely to just close it.)

**Comment by srivatsahg** [comment]
The Hindu calendar is based on the Lunisolar. There are quite a few versions of Hindu calendar based on the Geography(ex: North India and South India have different versions). However, the underlying concept remains the same. 

You can find the short introduction from the Wiki here
[https://en.wikipedia.org/wiki/Hindu_calendar](url)

I will collect some more information and share it with you in the coming days.

![image](https://user-images.githubusercontent.com/2742470/41389329-c477b052-6fad-11e8-86f4-1c372a8f972f.png)

**Comment by jskeet** [comment]
Having support for lots of similar calendar systems isn't much of a problem in terms of the implementation code, but it's more of a problem in terms of testing and making the API simple. (And on a minor note, using up calendar IDs, which are effectively limited to 64. It shouldn't be a problem unless there are a *lot* of them.)

If it's as simple as "One for North India and one for South India" that would be fine, but if it's 10 different ones that becomes more of an issue. That's why I'm asking which specific subset would be most useful to implement.

**Comment by jskeet** [comment]
Closing as obsolete due to lack of further information and interest.
