### ISSUE TITLE
Missing microsecond accessors

### ISSUE THREAD

**Issue by roji** [nodatime/nodatime#1121]
It would seem that NodaTime types in general are missing microsecond accessors and methods. LocalDateTime is a good example: there are `Millisecond` and `NanosecondOfDay` properties but no `Microsecond`. Same thing goes for `PlusMilliseconds()` and `PlusNanoseconds()`, but no `PlusMicroseconds()`.

I'm working on support for PostgreSQL, which represents timestamps at an accuracy of 1 microsecond so it's somewhat annoying, but I'm asking mostly out of curiosity.

**Comment by jskeet** [comment]
Yes, we somewhat-deliberately didn't add these - we weren't sure there'd be enough call for them. I don't massively object to doing so, but I'd probably like to wait to see if there's more call for them to start with.

For the moment, I'd suggest adding extension methods so you can keep all the conversions in one place. Let me know if there are any places where this turns out to be hard to do outside the library.

**Comment by roji** [comment]
Well, it's always possible to specify microseconds via nanoseconds so this isn't a blocker - more an issue of completeness. And unfortunately C# doesn't have extension properties.

Will leave this open for you to consider but feel free to close.

**Comment by jskeet** [comment]
I'm happy to leave it open to see if it attracts more attention. I might even write a prototype PR at some point, just so we can see how many more members it introduces. (I'm somewhat concerned that the API surface of Noda Time is already pretty huge.)

**Comment by jskeet** [comment]
Closing given that we haven't seen any more demand for this in more than 18 months.
