### ISSUE TITLE
Making DateInterval implement IEnumerable<LocalDate> is a breaking change

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime#1144]
It is nice to see that `DateInterval` is finally getting some more convenience methods, like an enumerator, intersection and union. However, adding the enumerator affects how extension methods are being resolved, causing code to now break.

As an example, consider this small unit test:
```c#
[Fact]
public void Test()
{
    var interval = Fixture.Create<DateInterval>(); // Let AutoFixture create a random DateInterval
    interval.Should().Be( interval ); // Use FluentAssertion to assert that the interval is equal to itself
}
```
With NodaTime <2.3 this compiled and passed just fine. The equals method would be used to check if the interval was equal to itself.

With NodaTime >=2.3, the extension method `Should()` is now called on the `IEnumerable<LocalDate>`, and returns an object (`GenericCollectionAssertions<LocalDate>`) which doesn't have a method called `Be()`, causing the code not to compile anymore.

It seems to me that the minor version bump from 2.2 -> 2.3 should have been a major bump to 3.0.

**Comment by jskeet** [comment]
By that definition, *any* public addition to *any* public type would count as a major version bump - I don't think that's practical. What counts as "breaking" is much more of a grey area than we tend to like to think of it, which means there are some judgement calls to be made. In this case, I'm pretty comfortable with the decision here. I accept it's breaking for this specific case, but I don't think it's "major version breaking".

**Comment by malcolmr** [comment]
It wasn't entirely clear to me from the above example, but the issue here is that Fluent Assertions (https://fluentassertions.com/documentation/) doesn't provide assertions for `object` when given a more-specific type.

That is, you can't write:

```
IEnumable<Foo> actual = ...
actual.Should().Be(expected);
```

but you (presumably) can write:

```
IEnumable<Foo> actual = ...
((object) actual).Should().Be(expected);
```

[In contrast, something like [Truth](https://google.github.io/truth/) for Java does still allow you to write `assertThat((Iterable<Foo>) iterable).isSameAs(foo)`.]

This seems like more of a limitation in Fluent Assertions to me.

**Comment by jskeet** [comment]
I'm going to close this now, but please feel free to try to persuade me further :)
