### ISSUE TITLE
Re-evaluate build scripts and system

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1182]
We have a lot of build scripts which are somewhat hacked together.

We should look at what we really need, particularly if we move the web site generation to a normal CI system rather than bagpuss, and then consider using Nuke Build, using https://github.com/nuke-build/convert-nodatime for inspiration.

**Comment by jskeet** [comment]
Note: we've now separated out all the web site stuff to the nodatime.org repo. The build scripts in this repo are now limited to:

- CI
- Building releases
- Updates due to time zone data
- Benchmarks

Most of this is now pretty simple, but possibly the tzdb-update part could be simplified further. (Just removing the versions we no longer update would help a lot...)

**Comment by eatdrinksleepcode** [comment]
Coming back to NodaTime after a _small_ break (my last commit was in July 2012...), and this open issue about build scripts caught my eye. I took a look at the `build` directory to see where things stand; here's a few thoughts as a "new" developer to the repo, with an eye towards maybe being able to close this issue. I realize that many of these are likely outside the original intended scope of this issue; I'm happy to open new issues if appropriate.

0. The OP mentions possibly adopting Nuke Build, but that was before the build was significantly simplified. Although I am in general a fan of build tools, I don't particularly feel that the current build warrants adding a dependency.
1. There is no easy way for me as a developer to run the build the same way that CI does (other than copying commands out of one of the CI build files; technically I can just execute `travis.sh`, because it makes no real assumptions about where it is running, but it is not obvious to a new developer that would work, and it might not in the future). There is also some redundancy between `appveyor.sh` and `travis.sh`. Having a script that encapsulates what CI sees as "the build" (e.g. `build.sh`) could be useful.
2. CI [skips "slow" tests](https://github.com/nodatime/nodatime/blob/bde354b020f7dbe9ac036d689bfe4b224ddce1be/build/appveyor.sh#L17) (the ones which verify an entire calendar), which are apparently [only run prior to release](https://github.com/nodatime/nodatime/blob/bde354b020f7dbe9ac036d689bfe4b224ddce1be/build/buildrelease.sh#L40). However, the [instructions for running the tests](https://github.com/nodatime/nodatime/blob/master/CONTRIBUTING.md#running-tests) don't mention the "NoSlowTests.runsettings" file, which on my machine drops the time for "dotnet test NodaTime.Test" from about 2.5 minutes to 40 seconds. It's also not necessarily easy to skip the slow tests when running through an IDE's test runner, and doing so would be IDE-specific.
It would be great if running these slow tests were opt-in instead of opt-out, which would make skipping them the default for developers. This could be achieved using the `Explicit` attribute instead of `Category`, or possibly by using `Assert.Ignore` (based on an environment variable?).
3. Probably a controversial one: using bash scripts has the nice property of making them runnable on multiples OSes, but it also requires Git Bash on Windows. Since the scripts are relatively simple, that probably isn't a big problem, but it is an additional dependency. Since they _are_ simple, one option would be to rewrite them as MSBuild tasks and invoke them via `dotnet build` instead, which would also be cross-OS and remove the dependency on Git Bash.
I don't particularly _like_ MSBuild, but I like unnecessary dependencies even less, so I am swallowing my distaste for the sake of the suggestion. If we want to keep the bash scripts, then we should document the dependency on Git Bash.
4. And finally, you (@jskeet) previously [mentioned](https://github.com/nodatime/nodatime/issues/1182#issuecomment-485067254):

    > the tzdb-update part could be simplified further. (Just removing the versions we no longer update would help a lot...)

    I assume that means the versions _of NodaTime_ that are no longer being updated. From nuget.org, I take it that only 2.4 and 3.0 are updated; so remove everything prior to that? Also do you have any other thoughts on how tz-update could be simplified?

**Comment by jskeet** [comment]
@eatdrinksleepcode: Responding in order:

0: Agreed, I don't think we need Nuke Build.

1: Yup, having a `build.sh` would definitely make sense. (It would also make it easier to move from Travis to GitHub Actions, which I want to do.)

2: Yes, that makes a lot of sense.

3. I *definitely* don't want to try to convert everything into MS Build. That would increase the maintenance burden *massively*, for very little benefit IMO. Almost no-one needs to run those scripts other than me; I believe it would cost me far more time than it would save anyone else. Note that the dependency on bash (not necessarily git bash - I believe most scripts work on Linux and Mac already), is only if you really want to run the scripts. If someone is just hacking on the main Noda Time project (which most contributors would do) then running `dotnet test NodaTime.Test` is sufficient. I'm happy to document the dependency on bash for the very few people who need it.

4. Yes, we could remove the old shell scripts. I'll do that later today. It's all still a bit fiddly within the scripts, but that's somewhat unavoidable due to "rebuilding the past" - it's much easier to have a single script for "whatever's current" than to remember what's changed over time and update that. I don't think there's much more in the way of low-hanging fruit.

Feel free to create separate issues or PRs for 1 and 2; I can edit https://nodatime.org/developer/building to mention bash.

**Comment by matkoch** [comment]
The dotnet bootstrapping is a bit of an oversight here. As of now, the project isn't "ready to hack" for everyone.

**Comment by jskeet** [comment]
@matkoch: When you say "dotnet bootstrapping" do you mean the requirement to have the .NET SDK installed? I'd expect most people interested in contributing to already have that, but I'd be happy to review a PR to make it all more accessible.

**Comment by eatdrinksleepcode** [comment]
@jskeet:

0,1,2,4: 👍 
3: Understood. I am biased here by my experience on the JVM with Gradle, where I would typically put additional build/release-related capability into the same tool as the build and test capability itself. This has advantages IMHO; but I understand that it is not the convention in .NET, mostly due to the limitations of MSBuild.

**Comment by matkoch** [comment]
@jskeet I also have the latest LTS installed, but I know a lot of people that just trashed all previous SDKs in favor of .NET 5. You're right that as an existing/long-time contributor, you will have that, but in the end, it's still a _requirement_ for the repository. If you agree, you can just copy the bootstrappers from nuke and remove the configuration and build project execution part ([build.sh](https://github.com/nuke-build/nuke/blob/develop/build.sh)/[build.ps1](https://github.com/nuke-build/nuke/blob/develop/build.ps1)). They're both very carefully documented.

@eatdrinksleepcode this is not about limitations of MSBuild but due to the complexity of adding logic through MSBuild and it often being fragile against different environments. `dotnet build` and `dotnet test` should always work as long as the project is compilable, and should not fail due to – I don't know – GitVersion having an issue with libgit2sharp or something.

**Comment by jskeet** [comment]
@matkoch: My experience of bootstrappers like this is that they get out of date quickly and become more trouble than they're worth. I'd prefer to *either* change global.json to allow the use of .NET 5, or just document "you need .NET Core 3.1 SDK to be installed" with a link to where to get it from. That's a minor change to CONTRIBUTING.md.

**Comment by matkoch** [comment]
@jskeet that's not my experience, and I work pretty intensively in this area :) There are also a bunch more benefits as explained here: https://ithrowexceptions.com/2020/07/01/road-to-cross-platform-setup-and-bootstrapping-in-dotnet.html

**Comment by jskeet** [comment]
@matkoch: The fact that you *do* work pretty intensively in this area suggests you're not exactly unbiased on this front though.

I really, really don't want to add complexity (and however well it is documented, a 71 line shell script *is* additional complexity) for something that we don't even know is causing any problems. I'll update CONTRIBUTING.md now to say "look at global.json to find out the version to install" but I want to leave it at that until I have evidence to suggest it's worth doing anything more.

**Comment by matkoch** [comment]
@jskeet I'm generally indifferent about the outcome, I just responded because the initial "dotnet test is enough" is not exactly accurate. I also did my best in the blog post to reference other opinions regarding that topic. Up from there, it's your choice :)

**Comment by eatdrinksleepcode** [comment]
@matkoch that's what I mean by "the limitations of MSBuild" :)

re: bootstrapping... While I am a big believer in making the initial experience for developers new to the repo as frictionless as possible, I also have a lot of sympathy for an independent library project maintained primarily by a single person not needing to take on the burden of supporting complex bootstrapping across a range of environments. Maybe one day Microsoft will treat this kind of "first-time experience" as a first-class citizen; or even better, maybe one day third-party build tools will become mainstream and we won't have to rely on Microsoft to get it.

But for now, where we are, I think clearly documenting the required dependencies is enough.

**Comment by eatdrinksleepcode** [comment]
As a point of reference, I did _not_ have the 3.1 SDK installed when I cloned NodaTime (I did have 5 installed). I was warned that I didn't have it (I think by Rider first), spent a few minutes trying to figure out how to do that from the CLI, eventually gave up and downloaded the official installer.

After that, Rider is still warning me about missing reference assemblies when I load the solution:

> Project 'NodaTime.Benchmarks' load finished with warnings: [MSB3644] The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks at (1177:5)
> Project 'NodaTime.TzValidate.NzdCompatibility' load finished with warnings: [MSB3644] The reference assemblies for .NETFramework,Version=v4.6.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks at (1177:5)

But it doesn't seem to affect the build, either from the IDE or the command line, so I am ignoring those warnings for now.

**Comment by jskeet** [comment]
@eatdrinksleepcode: Ah, I can probably fix that just by adding the reference assemblies as a package reference. Will try that in the morning.

**Comment by matkoch** [comment]
@eatdrinksleepcode i'm sorry but the comments don't add up for me. First, you called it an unwarranted dependency, then the bootstrapper is too complex to maintain by a project maintainer. So why not use a build tool then? (not directed to you @jskeet). A tool doesn't have to be mainstream to do a job well, imo. And if yes, please read a bit more about it and add it to your technology radar ;)

**Comment by jskeet** [comment]
@eatdrinksleepcode: Ah, I've just looked at the Benchmarks project, and it already includes the reference assemblies. So I suspect that warning is IDE-specific, and it's reasonable to just ignore it.

**Comment by eatdrinksleepcode** [comment]
> Feel free to create separate issues or PRs for 1 and 2

(Apologies for the delay; real life intervened)

@jskeet it looks like you took care of 1 as part of some work on GitHub Actions, which is a separate issue. I just opened #1625 for 2. Is there anything left that you know that you want to do for the build? If not, does it make sense to close this issue?

**Comment by jskeet** [comment]
@eatdrinksleepcode: I'll have a look at #1625 when I get a chance, and thanks for that.

I would still *like* to re-evaluate the build scripts at some point, but I can't see it happening any time soon, and I don't think this issue is particularly helpful to keep open - so yes, I'll close it now, thanks.
