### ISSUE TITLE
How can get a timespan like struct and output it to string format?

### ISSUE THREAD

**Issue by sgf** [nodatime/nodatime#1187]
i need convert  the months Number to output

> XX Years XX Months

even i can use
`(monthsNumber)%12`
 
but i still want to know how to do that in NodaTime ?

**Comment by jskeet** [comment]
`Duration` is the struct closest to `Timespan` in Noda Time - but that doesn't have a logical representation in terms of "years and months". For example, "30 days" could be 1 month or 0 months, depending on when it's based.

`Period` is a calendar-arithmetic-based struct, so *does* have years/months/days etc... but it doesn't normalize 12 months to 1 year, because not all calendars have 12 months in a year.

To take a number of months and convert it to a period while performing normalization, I'd just use:

```
public Period PeriodFromMonths(int months) =>
    new PeriodBuilder { Months = months % 12, Years = months / 12 }.Build();
```

**Comment by sgf** [comment]
thanks.😂
