### ISSUE TITLE
Need ZonedDate?

### ISSUE THREAD

**Issue by FDUdannychen** [nodatime/nodatime#1192]
Currently there are `LocalDateTime`, `LocalDate`, `ZonedDateTime`. There are workarounds without `ZonedDate`, though.

**Comment by mcapuozzo** [comment]
Perhaps this is a valid use case for ZonedDate/ZonedTime class, perhaps it isn't.

Let's say we have some software that coordinates real-time triggers simultaneously across multiplie time zones (perhaps even within the same UTC offset). And let's say that those triggers are supposed to occur daily. We could preserve that information in a ZonedDateTime struct, ignoring the Date portion. 

The reason for which I think a ZonedTime would make sense, however, is that it follows the semantic of the rest of your library. Local and Offset classes allow the user to model just the information that is necessary for a particular use case. Zoned is the odd man out.

In any case, I see your suggestion about making a struct with LocalDate and DateTimeZone, which will work perfectly. Thank you.

**Comment by jskeet** [comment]
If the triggers are meant to occur daily in *multiple* time zones, wouldn't you store a single LocalTime along with multiple zone IDs? I'm not sure I follow.

Beyond that, there's another issue with `ZonedTime` as a concept: a `ZonedDateTime` knows its offset, because it knows the date; a `ZonedTime` couldn't do so, and couldn't resolve ambiguities either... I can't see how it would offer much that you could do with it *beyond* just "here's the zone, here's the time". Almost all of the rest of the structs in Noda Time provide more abilities because they're more than just a composition. (OffsetDate and OffsetTime less than the others - they were only a recent addition, primarily to model XML schema values, which isn't the case here.)

I'm still happy to be convinced, but I'll need more at the moment - I do think sticking with composing LocalDate and DateTimeZone yourself probably makes more sense for now.

**Comment by mcapuozzo** [comment]
Thank you for the fast response. I see what you're saying about the ambiguities. I suppose, in reality, if I need to synchronize events across timezones, I am better off programming those events to Instants. A LocalTime plus multiple zones wouldn't necessarily produce synchronous events, if I understand correctly, as the LocalTime of 8AM in one timezone might be at a different Instant than in another zone.

**Comment by jskeet** [comment]
> I suppose, in reality, if I need to synchronize events across timezones, I am better off programming those events to Instants.

Not necessarily. It depends on what you mean by "synchronize events" - if you want to store that something will happen at (say) "8pm in Paris on November 30th 2021" then that's what should be stored wherever you're storing information, because if you convert to an instant *now*, you may find the time zone rules change (e.g. to go on permanent DST) before the event itself occurs. That's a somewhat different issue, but I don't think ZonedDate would help.

**Comment by jskeet** [comment]
Closing as I don't think I've seen a compelling use case for `ZonedDate` yet. We can always reopen if one shows up.

**Comment by tompazourek** [comment]
We're implementing a delivery date calculation process for orders, and the output of that is an estimated date of delivery. However, such date is always specific to the time zone of the customer. It doesn't contain time, because we cannot be so precise to know which time of day the delivery will happen.

An, in Russia, for example, it can be different date depending on where in the country you are located. I might be missing something but, here a `LocalDate`+`Zone`, aka `ZonedDate` feels like it would be a perfect fit. Because we need to know which date it is, and for which time zone it's applicable. What do you think?

**Comment by jskeet** [comment]
@tompazourek: I'm ready to be convinced, but I'm not sure that a `ZonedDate` would be significantly more useful than just composing a `LocalDate` and a `DateTimeZone` yourself. I don't want to end up with *every* possible combination in the library, just because it's very occasionally useful.

**Comment by tompazourek** [comment]
@jskeet Yes, I only believe it would be useful just as a composite -- to have a single value instead of two values. It's possible to work around it by having two values, or maybe a tuple. But that can be said for the `ZonedDateTime` as well.

It actually seems that NodaTime already has all the combinations that make sense, except of `ZonedDate`...

The way I see it is the following:

- We have three major kinds: `Local`, `Offset`, and `Zoned`
- And then we have three main types of values: `Time`, `Date`, `DateTime`

- `Local`
	- `Time`: `LocalTime` already exists
	- `Date`: `LocalDate` already exists
	- `DateTime`: `LocalDateTime` already exists
- `Offset`
	- `Time`: `OffsetTime` already exists
	- `Date`: `OffsetDate` already exists
	- `DateTime`: `OffsetDateTime` already exists
- `Zoned`
	- `ZonedTime`: does NOT exist
	- `ZonedDate`: does NOT exist
	- `ZonedDateTime`: already exists

So really, as I see it, there are 9 combinations, and the library already has 7 out of those 9. The only two combinations that are missing are `ZonedTime` and `ZonedDate`. We already have all the other.

I can imagine use-cases for both, although I haven't needed something like `ZonedTime` yet.

- `ZonedTime` would be perfect for something like -- execute this daily at `8:00` (and note we're in Prague time zone)
- `ZonedDate` would be perfect for something like -- delivery will happen on `30th April 2021` (and note we're in Prague time zone)

For me, for example, I don't see how `OffsetTime` and `OffsetDate` are useful... I would much rather see `ZonedTime` and `ZonedDate`. The zoned values make more sense to me than offset values when talking about times and dates, which cannot be converted into instants. For `DateTime` however, it's a different story, there I can see that `OffsetDateTime` makes sense...

The other types like `Duration`, `Period`, `Instant` don't make sense as `Local*`, `Offset*`, and `Zoned*`.

Where I would draw the line based on my intuition would be types like `AnnualDate` and `YearMonth`... There I could see that it could be somehow useful as `Zoned`, I can understand that it might be a bit too much, and very rare.

Anyway, hope this helps to explain my thoughts. But I understand my point of view might be different. 🙂

**Comment by jskeet** [comment]
> But that can be said for the ZonedDateTime as well.

Not really. There are lots of ways in which `ZonedDateTime` uses its components together. I doubt that `ZonedDate` would have such methods, given that it doesn't represent an instant in time.

> For me, for example, I don't see how OffsetTime and OffsetDate are useful

They're partly to make the XML schema representations more complete - those concepts *do* exist in XML schema, but zoned concepts don't. That was the argument that tipped me in favour of adding those types (which were very late to the party, as it were).

I definitely don't want to add `ZonedDate` and `ZonedTime` just for the sake of completeness, if they're not going to actually be used by a significant number of people. (It takes a *lot* of work to add full support for a type, including text representations, JSON formatting etc.)

I'd like to suggest that for the moment, you either create your own `ZonedDate` struct or just use a tuple. You can then get experience of what a built-in `ZonedDate` would actually bring to the table in terms of encapsulation beyond "it's one variable instead of two".

**Comment by BrunoJuchli** [comment]
For us, the value for `ZonedDate` would be for it to validate whether the date can exist in the zone.
Let's say you have a date picker and Samoan time zone and you pick Dec 30 2011. Doesn't work, b/c it doesn't exist. Fails fast, not at some point later when an async process tries to do something with the date.
Real-life relevance is probably lo-o-o-ow?
But I'm a sucker for failing early. It just makes life easier when unexpected things happen :-)

Currently I've implemented it like:

```C#
public readonly record struct ZonedDate
{
    public LocalDate Date => AtStartOfDay.Date;
    public DateTimeZone Zone => AtStartOfDay.Zone;
    public ZonedDateTime AtStartOfDay { get; }

    public ZonedDate(
        LocalDate date,
        DateTimeZone zone)
    {
        // AtStartOfDayInZone is used because it will throw a SkippedTimeException in case the
        // date does not exist in the timezone.
        AtStartOfDay = date.AtStartOfDayInZone(zone);
    }
}
```

It has the `AtStartOfDay` property only because convienent.
If implemented within NodaTime maybe there would be a more efficient way to implement this?

We can live well without it being part of NodaTime.

-----

In the delivery date example brought up [here](https://github.com/nodatime/nodatime/issues/1192#issuecomment-828973161)
it might be nice if you could have a `ZonedDate` for today and then do `ZonedDate.AddDays(3)` which returns you a valid date for the timezone.

I think if you were to do the same for LocalDate you could end up with Dec 30 2011, right?

**Comment by jskeet** [comment]
> Real-life relevance is probably lo-o-o-ow?

Indeed. I don't think I know of any other date/zone combinations where that would actually be relevant, at least right now - so the simplest option would be to hard-code the date and zone ID :) (And I haven't heard about any proposals for any zones to do something similar in the future - there aren't many that really *could* consider it.)
