### ISSUE TITLE
Round-tripping NodaTime objects

### ISSUE THREAD

**Issue by roji** [nodatime/nodatime#1221]
While working on generating code literals for the Npgsql Entity Framework Core provider (https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/667), I need to round-trip NodaTime objects, i.e. save them in some external format and then construct them back (more precisely, I need to generate C# code that constructs, say, an Instant from a given Instant - but that's not important).

This obviously varies from class to class. For Instant, I can call `Instant.ToUnixTimeTicks()` and pass the result to `Instant.FromUnixTimeTicks()`. However, a tick is 100ns, while NodaTime supports 1ns precision - so that would be a lossy operation. I could also use `ToUnixTimeMilliseconds()`, and extract microseconds and nanoseconds separately, adding them back to the destination Instant after constructing it back from the milliseconds value.

Other classes such as LocalDateTime seem to have similar complications. Have I missed something, am I going about this the wrong way? Does it make sense to think about adding more useful conversion methods? Although I imagine that Instant and friends cannot be represented with a single long, so it's probably not possible to convert them into a single external value.

**Comment by jskeet** [comment]
You should choose your own epoch, and take a `Duration` from that - which you can round-trip however you want. Different applications may have different requirements here in terms of the range of values supported. A 64 bit integer can hold nanosecond values representing +/- ~292 years. For some applications, that may be sufficient and significantly simpler than trying to round-trip a larger integer. For other applications, or where the requirements aren't known, the full Noda Time range may be required - in which case you could go via `Duration.Days` (int) and `Duration.NanosecondOfDay` (long).

We *could* expose `ToUnixTimeNanoseconds` returning a `BigInteger` (and a corresponding `FromUnixTimeNanoseconds` static method). It's not clear to me that that's a good idea though - it probably ends up meaning folks default to using the Unix epoch when that might not be the most appropriate epoch for them. They're simple methods to write in application code while we're deciding though:

```csharp
public static BigInteger ToUnixTimeNanoseconds(this Instant instant) =>
    (instant - NodaConstants.UnixEpoch).ToBigIntegerNanoseconds();

public static Instant InstantFromUnixTimeNanoseconds(BigInteger nanoseconds) =>
    NodaConstants.UnixEpoch + Duration.FromNanoseconds(nanoseconds);
```

`LocalDateTime` is slightly more fiddly, partly due to the calendar ID. You might want to split it into `LocalDate` and `LocalTime`:

- An Int32 number of days from some epoch (e.g. with Period.Between specifying PeriodUnits.Days), with the epoch represented in the target calendar system
- The calendar system ID
- The `LocalTime`'s NanosecondOfDay

Internally we definitely have code to represent a `LocalDate` as a number of days since the Unix epoch (and a calendar system); we could *potentially* expose that, but I'm nervous of it being used for inappropriate scenarios. I don't want anyone assuming Noda Time has and will always have a Unix epoch implementation, for example. On the other hand, I can see it as being useful for this sort of serialization work.

**Comment by roji** [comment]
Thanks for the guidance @jskeet, I'll definitely use it - BigInteger for representing Instant relative to `UnixEpoch` is perfect. I'll have to work on this for quite a bit of the NodaTime types, and will post back if I run into any particular challenges.

As to whether there's any value in integrating such serialization/deserialization-oriented APIs into NodaTime types - I tend to be skeptical like you. There doesn't seem to be huge value in doing so.

**Comment by jskeet** [comment]
Righto - will close this for now, but we can reopen if there's any further work to be done.
