### ISSUE TITLE
Bug in zoned date time parsing with RFC 3339 pattern

### ISSUE THREAD

**Issue by artfulsage** [nodatime/nodatime#1257]
Hi. I suppose there is a bug in parcing zoned date time with RFC 3339 pattern.  
This test fails. Checked in e5a6132cba77ad16b7b58f0d975a22f22d773f41

```cs
[Test]
public void Rfc3339ParseTest()
{
  var date = "2012-10-28T01:02:03.004000067+03:00";
  var textPattern = "uuuu'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFFFFo<Z+HH:mm>";
  var pattern = ZonedDateTimePattern.CreateWithInvariantCulture(textPattern, DateTimeZoneProviders.Tzdb);
  var result = pattern.Parse(date);
  Assert.IsTrue(result.Success);
}
```

**Comment by jskeet** [comment]
Thanks for the bug report. It's an odd failure - the exception if you try to fetch the value is:

> NodaTime.Text.UnparsableValueException: The specified offset is invalid for the given date/time. Value being parsed: '2012-10-28T01:02:03.004000067+03:00'.

I'll investigate now, and probably back port the fix to 2.4.x, but I'd suggest that as this doesn't really have a time zone, just an offset, you'd be best off parsing to `OffsetDateTime` - which *does* parse correctly.

**Comment by jskeet** [comment]
Ah, I see the problem now. Your pattern uses `o<Z+HH:mm>` which is an embedded *offset* - but no *zone* is present, so it's defaulting to UTC. You're expecting it to be parse as the zone, not as the offset. But "+03:00" isn't a valid time zone ID, so a pattern of `"uuuu'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFFFFz"` fails differently.

I think this situation basically isn't covered yet, so I'm going to treat it as a feature request rather than as a bug. As I mentioned before, the value being represented is *really* an `OffsetDateTime` rather than a `ZonedDateTime`, and it *can* be parsed as that. I'm not sure how far I want to bend things to allow it to be parsed as a value that it doesn't really represent.

**Comment by artfulsage** [comment]
Thanks for your clarification. Indeed `OffsetDateTime` is right choice for me.

**Comment by jskeet** [comment]
I think I'm going to close this for now, as parsing an `OffsetDateTime` as if it were a `ZonedDateTime` is almost never going to be the best approach.
