### ISSUE TITLE
PlusYears, Months, Days

### ISSUE THREAD

**Issue by TheMightyPope** [nodatime/nodatime#1265]
I love the package, and I understand the implications of adding a PlusYears, PlusMonths and PlusDays to the various types. I can see why they can be imprecise and ambivalent.

Now, that said, they are also incredible useful functions that are used all the time in regular C# for various purposes, even with all their pitfalls and rounding, and potential issues. 

I was recently forced to implement this, simply because I may sometimes need to add a year, month or date to a LocalDateTime, OffsetDateTime, or ZonedDateTime.  That's simple the source types I am stuck with. So I would LOVE to see these added to the functionality so I can avoid coding like this:

> LDateTime = LocalDateTime.FromDateTime(((LocalDateTime)LDateTime).ToDateTimeUnspecified().AddDays(X));

> OffsetDateTime.FromDateTimeOffset(((OffsetDateTime)UTCDateTime).ToDateTimeOffset().AddMonths(X));

>  DateTimeZone Z = ((ZonedDateTime)ZDateTime).Zone;
>                         ZDateTime = ZonedDateTime.FromDateTimeOffset(((ZonedDateTime)ZDateTime).ToDateTimeOffset().AddYears(X));
>                         ForceTimeZone(Z.Id);

That last one is another helper function I have that forces a timezone onto a ZonedDateTime.

I would be perfectly happy it the helper functions worked the same way C#'s DateTimeOffset does it, including it's rounding and whathaveyou. The reality is that these are incredibly useful functions that are sort of difficult to write using just NodaTime (as per my examples, which btw, are not tested yet, but probably close to what they will look like). You could add a bunch of warnings, maybe do the conversion AND throw an exception if anything ambiguous happens, etc.

Use Case: Reading an API with ZonedDateTime of Feb 29th 2000 8 PM Europe/Copenhagen, and need to show an alert one year later. 

That would be Feb 28th 2001 8PM Europe/Copenhagen if I used DateTimeOffset.AddYears(1). 

Feel free to shoot it down now :)

**Comment by jskeet** [comment]
There are two big reasons not to do this:

- Your "You could add a bunch of warnings [...]" sentence covers a great deal of application-specific logic. Noda Time can't make that choice for you. Some users may want exceptions, some may want to "round" to a valid time etc. That's why we have `LocalDateTime.InZoneStrictly`, `LocalDateTime.InZoneLeniently` and `LocalDateTime.InZone(zone, resolver)`. I definitely wouldn't want to have three overloads for each of `PlusHours`, `PlusDays` etc
- You really only want to perform that conversion back to a `ZonedDateTime` *once* after doing all the arithmetic involved. If you want to add "an hour and a day" then doing that in two steps with a conversion back to `ZonedDateTime` after each step could give weird results due to the handling of ambiguous/skipped times happening twice. We could *potentially* have methods just accepting a period, but I'd rather encourage users to handle it separately anyway.

Once you know how you want to convert from a `LocalDateTime` back to a `ZonedDateTime` it's really not that hard anyway. For example, adding a day and an hour:

```csharp
ZonedDateTime original = ...;
ZonedDateTime result = original.LocalDateTime
    .PlusDays(1)
    .PlusHours(1)
    .InZoneStrictly(original.Zone); // Or InZoneLeniently, or InZone with a resolver
```

That really doesn't look too bad to me - and it keeps flexibility without adding huge API surface.

If you want to add your own extension methods to do that, you're welcome to do so - but I'd advise against it unless you really find yourself doing this frequently. (Maybe add a single extension method accepting a `Period`.)

I would *strongly* advise against doing this by going via the BCL types though. Aside from anything else, Noda Time has greater range and greater precision than the BCL - and while you may not *currently* be working with any values that have sub-tick aspects other than zero, it seems a shame to lose that precision for no benefit. I suspect that going via the BCL is going to be slower than working in just Noda Time, too.

I'll leave this issue open for now, but I think it's at least *unlikely* that you'll persuade me on this one.

**Comment by TheMightyPope** [comment]
First of all, thanks for the correction., I agree it's better to not go through BCL types.

Let me explain where I'm coming from, perhaps for some perspective. I'm developing a very large project, and realized that I need to handle TimeZones, UTC, etc correctly. I'm dealing with a huge amount of data from a lot of external sources, which comes in (quite frankly) a plethora of formats. I detect their formats as best I can. Once that is done, I have either a Local, Offset, Instant or Zone variable, depending on what the input was. I also added my own BigYear (for millions of years ago).

For all of these, I quite often need to change the timezone (which now it easy, thank you very much), apply a timezone when I know what it is (and the API doesn't), or in some cases modify the date, like adding a year, month or day to it.

While researching NodaTime, I found the learning curve rather steep. I wish there were a TON more examples, use cases, conversions, etc, which would have significantly boosted the time to learn it, and to really "understand' it. In any case, I do get it now (What a mess DateTimes are).

From that, I still need to simple add a year, month, day in some cases, and that's why I asked. I understand the comment about having three functions for each, and the API growing. That's your choice of course to keep it small and sweet. I'm thinking, to get broader use of NodaTime, have more developers jump on quickly, I would be more than happy having the functions just use leniently and call them something like AddYearLeniently, and just have one such function. It would simply save developers time to to learn, it would work for 95% (I'm guessing) of users that are at least better of than DateTime, and it would simplify code everywhere. I'm thinking some of these convenience functions gets more people on-board with the project easier, and from there they can gradually move to the more complex handling.

I've solved my issues, so it's not a big deal to me personally anymore, but I would love to see NodaTime spread, and making that easier I think is an argument. Of course, an argument you can safely ignore :) I trust your judgement on this.

More examples and use case would be really appreciated though

**Comment by jskeet** [comment]
No, I really don't want to *just* add the "leniently" methods. Because then that won't work for everyone, so we'll need to add the strictly methods. And then the other methods. And at that point, over half of the `ZonedDateTime` API would consist of methods I'd want to discourage people from calling anyway, because of the "multiple conversions if you perform multiple operations" problem. I could just about live with a single `Plus(Period)` operation across strictly/leniently/with-a-mapping-resolver, but I wouldn't want to do anything more than that. Generally I'd prefer to discourage calendrical calculations over `ZonedDateTime` - I find they're *rarely* the right thing to do. They may be right for you, but I wouldn't want to encourage people to use them in other situations.

For those who *do* need these operations, they're very easy to add as extension methods - so I'd rather keep the API "lean" in this way.

In terms of more examples etc - yes, I'd love to provide more, but I'm only one person and I have a very full schedule. Pull requests providing more examples are very welcome...

**Comment by TheMightyPope** [comment]
Thanks Jon, 
I'll try and find the time to get some examples together for you.
