### ISSUE TITLE
BCL support under NetStandard2.0

### ISSUE THREAD

**Issue by TheMightyPope** [nodatime/nodatime#1273]
I have a project using NetStandard2.0, and it seems DateTimeZoneProviders.Bcl is not supported, I get this compile time error:

> var blc = DateTimeZoneProviders.Bcl;

'DateTimeZoneProviders' does not contain a definition for 'Bcl'	SAWCommon(netstandard2.0)	
(SAWCommon is my project name, as you can see, NetStandard2.0)

I understand that NetStandard1.3 is not supported as [per documentation](https://nodatime.org/2.4.x/userguide/limitations), and while I'm not sure exactly which function it is that is needed, I think they _may_ be supported in NetStandard2.0.

I'm guessing it's this one, which I can call successfully in my project.

> TimeZoneInfo.FindSystemTimeZoneById("US Eastern Standard Time")

Will it be possible to support this in NetStandard2.0 ? If yes, YAY. If no, I suggest updating documentation to also mention version 2.0 is not supported.

**Comment by jskeet** [comment]
The intention of introducing netstandard2.0 support in 2.4 was *solely* to give a more pleasant experience to those depending on netstandard. It's exactly the same code as the netstandard1.3 target, so it doesn't support `DateTimeZoneProviders.Bcl`. So yes, I definitely need to update the documentation, at least.

It would be *possible* to support `TimeZoneInfo` in the netstandard2.0 build - but it would take a certain amount of work. In particular:

- I'd need to check all the conditional code. At the moment it's all just conditional between two options (netstandard or not); to really support three options I'll need to look carefully at each place
- I'd need to back port some of the changes I made in `BclDateTimeZone` from the master branch into a 2.x branch (this would be 2.5, realistically)

So yes, I *can* do that - but that'll take time that could otherwise be used on 3.0. That *only* targets netstandard2.0, so has no conditional code at all, and still supports `DateTimeZoneProviders.Bcl`. However, it'll be a while before it's ready to ship. I'm pretty confident of all the code that's in there at the moment, but there are other things I want to do before a 3.0 release.

I'd be happy to create an alpha or beta release of 3.0 if that would help you, but if you need a combination of a GA release and the use of `DateTimeZoneProviders.Bcl` when targeting netstandard2.0, that would need a 2.5 instead. (At that point I'd probably add the type converter work in too.)

Could you let me know more about your context so I can prioritize?

**Comment by TheMightyPope** [comment]
The reason we need it is because we deploy to AWS Lambda's, which only supports NET CORE, and recently netstandard2.0. So essentially anyone using AWS Lambda's can't use Nodatime if they need the BCL timezone support. We specifically need it to convert from some of many many external API's who insists on using the BCL timezones (yes, sigh!!). 

For the main part we use NodaTime now to correctly interpret timezones and UTC, and parse them as well, plus conversions. We're perfectly happy using version 2.4.4, so if it's 3.0 or 2.5 doesn't matter much to us (We're not craving any 3.0 features). As long as 3.0 is non-breaking from an API perspective and supports essentially the same as 2.4.4 (and is not overtly buggy), well then a 3.0 would be great 

I suppose we're happy anyway you can support this, and very much appreciate it.

**Comment by jskeet** [comment]
There *are* breaking changes between 2.x and 3.0, otherwise it wouldn't be 3.0 - but I don't expect them to affect most people.

The most important part is changing to *only* support netstandard2.0 of course. But additionally we've dropped binary serialization support. API changes are in https://nodatime.org/unstable/api/changes.html, but that's basically it so far :)

The choice isn't really "2.5 or 3.0" - it's "a 2.5 GA in a few weeks, or a 3.0 beta in a few days". If you're happy with a beta version, I'd definitely prefer to do that as it takes a lot less time. The 3.0 code really should be at least as good as 2.4 at this point - although I've made a lot of changes recently to use new C# 8 features, I haven't done any significant refactorings. (I'm likely to do so later to support spans, but that's in the future.)

**Comment by TheMightyPope** [comment]
The breaking changes shouldn't affect me as far as I can tell, HOWEVER, I managed to do a few workaround for the API's that affect me, and I'll hate to have you spend time just for my sake, so while a 3.0 release would be great, I'll say don't do it just for my sake. I can wait for the official version. Thanks for offering though.

**Comment by jskeet** [comment]
Wonderful, thanks. Will leave this open for the moment for the sake of remembering to update the documentation.
It's probably useful to publish an early 3.0 prerelease soonish anyway, for folks who want to investigate how C# 8 support works with external libraries.

**Comment by TheMightyPope** [comment]
Well, I won't object either :)
