### ISSUE TITLE
New LocalMonth type

### ISSUE THREAD

**Issue by artfulsage** [nodatime/nodatime#1311]
Hi. Sometimes we need to operate with data related to month when only month and year matter - store it or filter. For example some month user activity.

Now we have to use `LocalDate` (1st day of month) for database mapping and our custom wrapper based on `LocalDate` with implementations of `IModelBinder` and `Newtonsoft.Json.JsonConverter<T>` for Web API.

It would be great if there was a special data type for such cases. And I'm sure after adding this new type soon there will be added database mapping and json serialization for it.

**Comment by jskeet** [comment]
If we *were* to do this, I'd want to call it `YearMonth` instead of `LocalMonth`. But I'm not yet convinced it's worth doing at the moment. Every time we add a type to the API, that has a cost not just in terms of implementation but also in terms of API surface complexity.

I'm not saying it wouldn't be useful to some developers - but I'm not yet convinced it's useful for *enough* developers to warrant its inclusion.

> And I'm sure after adding this new type soon there will be added database mapping and json serialization for it.

This sounds like you think support just happens organically. The reality is that it takes effort to add any feature, and then maintenance effort too. It's not something I want to take on lightly.

**Comment by artfulsage** [comment]
I understand your point and appreciate you have considered this suggestion. Maybe someday anybody else would ask the same feature. And can I make a PR for this someday later?

**Comment by jskeet** [comment]
Yes, if you want to make a PR for it that would at least reduce the cost. I'm happy to keep it open to see whether other users want the same feature. (I'll check to see if we have other feature requests to merge this with.)

**Comment by jskeet** [comment]
Related: #317, ported back Google Code a long time ago. (We'd since implemented AnnualDate.)

**Comment by nheath99** [comment]
I would use this feature for my NodaTime Blazor Date/Time picker (https://github.com/nheath99/BlazorNodaTimeDateTimePicker) to represent the currently selected or displayed month. Not essential but certainly feels like a useful type.

**Comment by jskeet** [comment]
@nheath99: Thanks for the feedback. That does feel like a good use case. I may prototype a PR just to see what it feels like.

**Comment by carlosschults** [comment]
At my day job we've had use cases for a type like this. The solution was to create a custom struct.

**Comment by jskeet** [comment]
Just to confirm, this is in the works now. I'm *not* planning on backporting it to 2.x though. I'll happily release another 3.0 alpha once it's done, if that would be useful to folks.

**Comment by artfulsage** [comment]
Is there any news about release 3.0 date? I'd like to ask about this new class support in https://github.com/npgsql/efcore.pg

**Comment by jskeet** [comment]
No predicted date, I'm afraid. The main thing that needs resolving before 3.0 is what we do with `Span<T>` and patterns. I've got a prototype of how that could work, but it's not really ready to merge (and has performance degredation). I might try to find some time to prototype "how we can get away without it in 3.0 but add it in a non-breaking way in 3.1" in order to get a 3.0 release sooner.

**Comment by jskeet** [comment]
@artfulsage: I've done a prototype for deferring the `Span<T>` work, but it feels like a bit of a hack. I'm now wondering whether it might be best to look over everything I've done in terms of features and bug fixes since 3.0, and releasing them in 2.5 after all, to give more breathing space for 3.0 to be a clean break with everything I want in it.
