### ISSUE TITLE
Instant Documentation (2.4.x)

### ISSUE THREAD

**Issue by mrlife** [nodatime/nodatime#1314]
I was expecting a constructor and fields here but don't see them:

https://www.nodatime.org/2.4.x/api/NodaTime.Instant.html

Looks like they are on the old docs:

https://nodatime.org/1.3.x/api/NodaTime.Instant.html

**Comment by jskeet** [comment]
The documentation is correct. Those members are not public in the [2.4 code](https://github.com/nodatime/nodatime/blob/2.4.x/src/NodaTime/Instant.cs) (or any 2.0+ code). Instead, use the static factory methods (`FromUnixTimeSeconds`, `FromUnixTimeTicks` etc) to construct values if you *have* a value since the Unix epoch, and use the `ToUnixTimeSeconds()`, `ToUnixTimeTicks()` etc methods to convert the other way.

Other resources:

- [Complete list of changes from 1.4 to 2.0](https://nodatime.org/2.0.x/api/changes.html)
- [Migration guide from 1.x to 2.0](https://nodatime.org/unstable/userguide/migration-to-2)
