### ISSUE TITLE
Why does IPattern<T> have an AppendFormat method?

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime#1433]
I recently implemented `IPattern<T>` for one of my own types (which wraps a `LocalDate`) and was surprised to have to implement `AppendFormat()`. It was quite easy, as I just delegated to the underlying pattern I was using, but I was surprised I needed it. I would have thought that all implementations of `AppendFormat()` could be written as:

```c#
public StringBuilder AppendFormat(T value, StringBuilder builder)
{
    builder.Append(Format(value));
    return builder;
}
```

In which case it could work as an extension on `IPattern<T>` instead of requiring implementers to write that.

Am I missing something?

I'm probably unusual in implementing `IPattern<T>` myself, and if it bothers me too much I could always add my own interface, so it's not a big deal. I'm more interested in the reasoning than anything else.

**Comment by jskeet** [comment]
It *could* be written that way - but then it would always end up allocating a new string. This is an optimization, so that compound format strings that are "currently formatting using a StringBuilder" can just use the existing builder, instead of allocating a whole new string and then appending that. It also means that anyone else doing formatting with a StringBuilder can make use of the same optimization - e.g. if you're building a log entry that always starts with a timestamp.

If we were only targeting .NET Core, we could make this a default interface method as of C# 8, but I don't want to impose that limitation.

The alternative would be to put that method in an internal interface instead, but I think the benefits are worth the relatively low cost. (As you say, you're fairly rare in terms of implementing the interface yourself.)

**Comment by DanCarterGMSL** [comment]
Thanks for the response. That makes sense! :)
