### ISSUE TITLE
PCL version with updated TimeZones

### ISSUE THREAD

**Issue by tetri** [nodatime/nodatime#1438]
We are using version 1.4.7 as it is PCL and we are facing outdated time zones.
Is it possible to update the time zones in that PCL version?

**Comment by jskeet** [comment]
I believe that's a bit of a nightmare in terms of tooling, unfortunately.

However, you can still use more recent time zones - you just need to fetch the data file from https://nodatime.org. See https://nodatime.org/unstable/userguide/tzdb for details.
If you don't want to do this dynamically in your application, you could easily create your own NuGet package with a dependency on 1.4.7 that had the latest nzd file baked in as a resource. You'd then create a static class that exposes a `DateTimeZoneProvider` created lazily from that resource. When the nzd file is updated, you just update your package.

Does that work for you?

**Comment by tetri** [comment]
Oh hi Jon, it's a honor to be answered by you!
I'll definitely try that solution.
With the solution of this problem would not be feasible to release PCL version 1.4.8?

**Comment by jskeet** [comment]
I'm now sure what you mean by this:

> With the solution of this problem would not be feasible to release PCL version 1.4.8?

... but my sincere hope is that we don't need to release PCL version 1.4.8, because doing so will be a lot of hassle on my side.

**Comment by tetri** [comment]
I understand.
Thank you anyway ;)

**Comment by tetri** [comment]
> I believe that's a bit of a nightmare in terms of tooling, unfortunately.
> 
> However, you can still use more recent time zones - you just need to fetch the data file from https://nodatime.org. See https://nodatime.org/unstable/userguide/tzdb for details.
> If you don't want to do this dynamically in your application, you could easily create your own NuGet package with a dependency on 1.4.7 that had the latest nzd file baked in as a resource. You'd then create a static class that exposes a `DateTimeZoneProvider` created lazily from that resource. When the nzd file is updated, you just update your package.
> 
> Does that work for you?

Jon, do you have or indicate any material or website that has more detailed instructions on how to update nzd file dinamically in my Android Xamarin app?

**Comment by jskeet** [comment]
The link shows how to load an nzd file from a stream and create a provider from it. The rest will be your application logic - I can't really give you a sample of exactly what the code will be, because I don't know what you want to do, exactly. For example, you may well want to just ship a file with each release of your application, rather than pinging the NodaTime web site from your app. That would be the simplest approach, if you're releasing new versions of your application often enough that users won't get out of date.

Otherwise, you'd want to keep a file on the user's system with "the last version you downloaded" - along with its URL so you can always ping https://nodatime.org/tzdb/latest.txt and know whether or not to download a newer version. If you *do* find there's a newer version, again the behaviour will depend on your application - you *may* want to immediately use it, or you may want to just store it for the next time the app is opened. Or you may want to do this *when* the app is opened, and wait until you've got the latest file before proceeding. Do you need to check periodically while the app is open? I can't tell, because I don't know enough about your app. I hope you see now why there aren't any more detailed instructions - the code won't be terribly complicated in any case, but you need to make the decisions about what your app is going to do.

**Comment by jskeet** [comment]
Closing as we don't intend to release another 1.x build.
