### ISSUE TITLE
CompositePattern is useful - we should expose this functionality externally

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#147]
```
Use case: parse a value which is in one of many formats.

See http://stackoverflow.com/questions/13316142
```

Original issue reported on code.google.com by `jonathan.skeet` on 11 Nov 2012 at 9:04

**Comment by lundmikkel** [comment]
Is this still not possible?

**Comment by jskeet** [comment]
@lundmikkel: Not sure what you mean by "not possible" - we *could* expose it, but we still haven't done so yet. (If we do so, it would be for 2.0 rather than 1.3; we could potentially do it in 1.4 as well.)

**Comment by lundmikkel** [comment]
Yeah, by possible I meant, if it was possible for users of the library to use it. [As we talked about elsewhere](https://github.com/nodatime/nodatime/issues/607), it seems that composite patterns could solve some problems, that are otherwise hard to solve. Especially when `ParseResult<T>` is also internal.

**Comment by jskeet** [comment]
Yup - the ISO case is a particularly compelling one. It's niche, sure - but handy. Will need to check the API carefully, but I think I should be able to get this into 2.0.0.
