### ISSUE TITLE
WeekStartDay can be changed in different calendars

### ISSUE THREAD

**Issue by behzadian** [nodatime/nodatime#1472]
I tried to find a way to find start day of week with calendar, but it seems does not supported.
Please note in Iran, weeks starts from Saturday & ends in Friday. I need to know which day is start day of week

**Comment by jskeet** [comment]
That isn't included in `CalendarSystem` because it's not specific to the calendar system on its own, but also to the culture. Many countries use the Gregorian calendar system, but some treat Monday as the start of the week, and some treat Sunday as the start of the week - indeed, even within a single culture, different uses will have different starts. (For example, in the UK, a church is likely to consider Sunday to be the start of the week, but a business is likely to consider Monday to be the start of the week.)

Given that ambiguity, it's not really feasible to encode it in Noda Time.

**Comment by jskeet** [comment]
(I won't close this just yet, as you may have some ideas about what we *could* do that would be useful - but I suspect this is basically something you'll need to handle appropriately for your application.)

**Comment by jskeet** [comment]
Note that you can use `CultureInfo.DateTimeFormat.FirstDayOfWeek` to get a `DayOfWeek`, then convert that into the `IsoDayOfWeek` as used by Noda Time.

**Comment by behzadian** [comment]
Thanks! if this works, there is no need for first day of week!

**Comment by jskeet** [comment]
Okay - I'll close this now as I don't think there's anything to do in Noda Time.
