### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by Leon99** [nodatime/nodatime#1480]
I've been using NodaTime for a while now. I generally like its approach - it makes me think about things that could easily be missed and result in incorrect behavior. There is just one problem - its appeal to developers used to System.DateTime & Co. Occasionally, things work very different and seem counterintuitive. Here's the latest example: when doing addition/subtraction with System.DateTime, it works pretty much as expected, at least in terms of math, i.e. a-b=-(b-a). Math in NodaTime violates that due to the use of the ambiguous units and rounding up, and I don't see why it should. I mean - there must be a really good reason and complete lack of alternatives to violate basic math laws that everyone learns early on in their lives, and I really don't see why NodaTime would not respect that as there are a few different solutions possible:
1. Introduce System.TimeSpan alike type that, unlike Period, doesn't have months and years and is used when math is performed
2. Don't use months and years on Period when doing math (e.g. implement subtraction as `Period.Between(a, b, PeriodUnits.UnambiguousUnits)`)

Apologies in advance if I'm missing something here, but after reading the documentation and https://blog.nodatime.org/2010/11/joys-of-datetime-arithmetic.html I still don't see a reason good enough to violate the math laws and make transition from .NET's standard library more problematic.

**Comment by jskeet** [comment]
1. We already have `Duration` as an equivalent to `TimeSpan` but with nanosecond precision. If you want to perform non-calendrical arithmetic (e.g. between `Instant` values) then `Duration` is what you want.
2. If *you* want to perform arithmetic without using months and years, go for it - but I don't see why you should be able to impose that restriction on everyone else. Wanting to know the difference between two dates as a period with "some reasonable way of computing it" is a reasonable requirement; ditto adding periods.
3. If you think `DateTime` avoids this completely, please guess what the result of `new DateTime(2020, 1, 30).AddMonths(1).AddMonths(-1)` is. It should be January 30th, right? After all, adding something and then subtracting the same thing should get you back to the first answer... but no, it's January 29th (as it would be in Noda Time). That's pretty much unavoidable. Where Noda Time introduces more oddities, it's because it introduces more functionality - functionality that's desired by users.

The way the arithmetic works is [documented](https://nodatime.org/2.4.x/userguide/arithmetic) and reasonably easy to predict. There are more complicated approaches which may give "better" answers in some cases - java.time has one of these, for example - but I'm still reasonably happy with the system we've got, and I definitely wouldn't want to change the behaviour now, as a very subtle type of breaking change.

**Comment by Leon99** [comment]
Thanks @jskeet, I understand your point of view and all the considerations you mentioned. Let me clarify the use case. I want to do some basic math with `LocalDate`/`LocalDateTime`. I expect that to be pretty straightforward math that works according to the general math laws, but calculation of the ambiguous units in Period makes it much more complicated. `Duration` seems to be oriented at `Instant` and `ZonedDateTime`, not sure why though - is there a reason to prefer `Period` for operations with Local types?
To be clear - I'm not necessarily looking to introduce some changes, I'll be more than happy if there is a rational explanation that I could convey to others when "selling" them NodaTime. Everyone understands that AddMonths() is not a subject to the math laws, but there are certain intuitive expectations from using +/- operators, so it's different.

**Comment by jskeet** [comment]
> Duration seems to be oriented at Instant and ZonedDateTime, not sure why though - is there a reason to prefer Period for operations with Local types?

Yes - Local types are inherently calendar-oriented, which is where things get messy. Time zones then make things messier - the same `LocalDateTime` can occur twice in a day, or be skipped, so Duration-oriented calculations using `LocalDateTime` would be implicitly "assuming a time zone with no offset changes"... that's a dangerous assumption, so I make it harder to write code that does that. (If you want to use a duration, just convert both local values into UTC first. It's not hard, but that one extra step makes it explicit.)

>  Everyone understands that AddMonths() is not a subject to the math laws, but there are certain intuitive expectations from using +/- operators, so it's different.

I think once you understand that `DateTime.AddMonths()` doesn't follow normal expectations around math rules, it's easy to see that `date + Period.FromMonths(1)` would behave exactly the same, for the same reason. Most of the tricky aspects are from performing calendrical subtractions, which `DateTime` doesn't support but which are useful - and I don't believe it's possible to make those useful but also consistent with regular maths laws.

**Comment by Leon99** [comment]
So your view is that there is a demand for implementing plus/minus operations for months/years, and math with all other units should behave in a certain consistent way, is that right?
Just to clarify, my view is that something like calculating a number of days between two dates should be simpler than `Period.Between(lastDate, today, PeriodUnits.Days).Days`, and with `DateTime` it's as simple and intuitive as `(today - lastDate).Days`, and this is a much more typical operation than finding out how many years/months in a period.

**Comment by jskeet** [comment]
> So your view is that there is a demand for implementing plus/minus operations for months/years

Yes. Look at the many, many Stack Overflow questions for determining age, for example. (Most of which have incorrect answers involving DateTime.)

> and math with all other units should behave in a certain consistent way, is that right?

I believe that's the case.

> Just to clarify, my view is that something like calculating a number of days between two dates should be simpler than Period.Between(lastDate, today, PeriodUnits.Days).Days

That sounds like a vote for #1450. Admittedly that issue was raised for efficiency reasons more than anything else, but it would still meet your requirements.

> and with DateTime it's as simple and intuitive as (today - lastDate).Days

Except that's really error-prone, due to the Local/Unspecified/Utc aspect. If you get this wrong (e.g. subtracting a Utc DateTime from a Local DateTime or vice versa) you can easily get an off-by-one error.

> and this is a much more typical operation than finding out how many years/months in a period.

I'm not confident in that assumption. I don't think it's necessarily wrong, but I don't see any evidence either way.

**Comment by Leon99** [comment]
Thanks for detailed explanation, at least now I understand the logic behind the implementation. #1450 definitely would make my example slightly better.
