### ISSUE TITLE
Support for partial Date

### ISSUE THREAD

**Issue by weitzhandler** [nodatime/nodatime#1503]
Hi,

Please add a type that enables nullable portions of date, for example, we should be able to set 'month' and 'day', while leaving 'year' null (e.g. Anniversary: 21 May), or set only 'year' (e.g. Born 1912), or 'year' and 'month' only (Died in May 1972) while the rest is null.

I always bump in the need for this when dealing with genealogical data, or optional date data (e.g. birth or death date), where we have to give the user to choice of what data is available to them.

You might want to consider partial-time, and partial-date, then partial date-time that comprises of the two.

Once there, it'd be beneficial to have ranges too: `DateRange(PartialDate rangeStart, PartialDate rangeEnd)`.

[Related SO question](https://stackoverflow.com/questions/23677461/is-there-a-way-to-represent-partial-dates-in-noda-time).

**Comment by jskeet** [comment]
I'm not completely averse to the idea, but I'm not sure what we could actually provide. Since that Stack Overflow question was written, we've added YearMonth and AnnualDate, and there's a [separate feature request for Year and Month](#1468) but those are all quite different from having a type where any bits can be missing *within the same type*. I'm not sure what functionality Noda Time could really provide with that - and in particular, ranges don't have very many useful features.

Rather than us implementing something which doesn't really meet your requirements, I suggest you write your own type that maybe has conversions to/from Noda Time types, and has all the functionality you need - and when you've got experience with that and consider it "reasonably complete" you could potentially create a pull request to add that to Noda Time. Is that okay?

**Comment by weitzhandler** [comment]
Hey @jskeet and thanks for your quick and kind reply,

Personally I think ranges could be out of scope, but partial date looks to me like a proper fit into NT. If you don't agree, please clear the repo's desk by closing this issue. It'll remain here if some-else encounters a similar request and will save him time.

**Comment by weitzhandler** [comment]
> and there's a [separate feature request for Year and Month](#1468)

You must've been referring to #1468.



> and when you've got experience with that and consider it "reasonably complete" you could potentially create a pull request to add that to Noda Time. Is that okay?

That makes perfect sense.

**Comment by jskeet** [comment]
> You must've been referring to #1468.

Yup, fixed the link now.

**Comment by weitzhandler** [comment]
Updated my post too ;)

**Comment by bytenik** [comment]
I wrote the original StackOverflow question. And while in the last 6 years I've trended more towards TypeScript development than C#, every time I work in C# I end up using Noda Time, and every time I end up working with Noda Time I end up bumping into this same issue. I think the main functionality beyond the storage type itself would be comparisons with a concrete `Instant`. Things like YearMonth and AnnualDate help, but, sometimes both a fully specified time _or_ part of one are both permissible. An example is birthday; perhaps I want to store a user's full birthday, but for some people I only have birth month and year. Regardless, I want certain logic to happen during a user's birth month.

**Comment by jskeet** [comment]
@bytenik: I can see that, but I still don't think Noda Time is in a position to help. I suspect developers with that sort of situation have very different requirements - so I'd be surprised if we could create a type that folks would actually find useful. Your example of "comparisons with a concrete Instant" is a good one - that's just not feasible when you only have partial information; at least not in a normal `IComparable` way. Unless you'd want it to return a positive or negative number if it was *certain*, and null otherwise, for example - but would that be the behavior everyone else wanted too?

At the moment, while I can't really see the shape of what such an API would look like (and no-one has come forward with a proposal) I think the logic is probably best created outside Noda Time, to satisfy the concrete needs of each project.

**Comment by jskeet** [comment]
Closing for now, as I don't expect to do anything on this - I'm not convinced there's a sufficiently general set of operations we'd want to expose.
