### ISSUE TITLE
Check/document how binary compatible 3.0 really is

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#1525]
As mentioned in the conversation in https://github.com/nodatime/nodatime.org/pull/78, the addition of the `System.Runtime.CompilerServices.Unsafe` dependency _may_ cause Noda Time 2.0/3.0 not to be binary compatible with each other.

Per discussion, check whether 3.0 is actually binary compatible in practice as a result, and whether or not this is conditional upon the choice of runtime (for example, perhaps it's broken when using .NET Framework, but .NET Core is okay?) or on whether the caller is making direct use of XML serialization (which is the only feature using this).

(Jon's agreed to try out a few scenarios to see what happens in practice.)

Afterwards, we may want to update the documentation (https://nodatime.org/unstable/userguide/migration-to-3) to clarify whether users should expect to be able to drop in a `.dll` into an existing deployment.

**Comment by jskeet** [comment]
As a thought: given that we've removed the .NET Framework target, it's possible that xcopy deployment ("just copy the dll") is *entirely* broken. This could be interesting.
The more interesting binary compatibility story IMO is "application depends on library X and NodaTime 3.0; library X depends on NodaTime 2.4.8 but doesn't use binary serialization". I definitely want that to work - but agree we should know what happens in "copy the DLL" cases too.

**Comment by jskeet** [comment]
If we wanted to use `unsafe` directly again, here's the blog post where I show what the code would look like: https://codeblog.jonskeet.uk/2018/03/02/implementing-ixmlserializable-in-readonly-structs/

**Comment by jskeet** [comment]
Okay, test 1:

```csharp
using NodaTime;
using System;

class Test
{
    static void Main()
    {
        LocalDate date = new LocalDate(2020, 5, 16);
        Console.WriteLine(date);
    }
}
```

- Compile against 2.4
- Run - fine
- Copy 3.0 DLL in place
- Run: bang, "System.IO.FileLoadException: Could not load file or assembly 'NodaTime, Version=2.4.8.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1' or one of its dependencies."
- We at least need a binding redirect, which is expected
- Try adding a binding redirect:

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NodaTime" publicKeyToken="4226afe0d9b296d1" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-2.4.8.0" newVersion="3.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

- Success!

**Comment by jskeet** [comment]
Test 2: use XML serialization...

```csharp
using NodaTime;
using System;
using System.Xml.Serialization;

class Test
{
    static void Main()
    {
        LocalDate date = new LocalDate(2020, 5, 16);
        XmlSerializer serializer = new XmlSerializer(typeof(LocalDate));
        serializer.Serialize(Console.Out, date);
    }
}
```

Works as per test 1.

**Comment by jskeet** [comment]
Test 3: use XML *deserialization* (which requires the unsafe code)

```csharp
using NodaTime;
using System;
using System.IO;
using System.Xml.Serialization;

class Test
{
    static void Main()
    {
        XmlSerializer serializer = new XmlSerializer(typeof(LocalDate));
        string xml = "<LocalDate>2020-05-16</LocalDate>";
        object result = serializer.Deserialize(new StringReader(xml));
        Console.WriteLine(result);
    }
}
```

This time, it fails:

```text
Unhandled Exception: System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at NodaTime.LocalDate.System.Xml.Serialization.IXmlSerializable.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLocalDate.Read1_LocalDate()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Test.Main()
```

Even adding an assembly binding redirect and a copy of the most recent DLL doesn't help here. Hmm.

**Comment by jskeet** [comment]
According to https://github.com/StackExchange/StackExchange.Redis/issues/1130 there was an issue with binding redirects for System.Runtime.CompilerServices.Unsafe. As we haven't released anything to GA that depends on it yet, we can:

- Remove the dependency entirely (making XML deserialization very slightly less efficient, and requiring unsafe compilation - but making us dependency-free again)
- Update the dependency to the latest version, which may bypass the issue.

Pinging Marc Gravell who will know more.

**Comment by jskeet** [comment]
In terms of compatibility though, there's another problem:

```text
csc Test.cs /r:NodaTime.dll
```

doesn't work due to moving from mscorlib.dll to System.Runtime.dll, so this *could* break some builds. I'd expect anyone using regular msbuild to be okay. I don't expect we'll change this aspect - it's just part of targeting netstandard2.0.

**Comment by jskeet** [comment]
Hmm. Removing the dependency may not be terribly simple after all. We can do it for everything apart from ZonedDateTime (see [blog post](https://codeblog.jonskeet.uk/2018/03/02/implementing-ixmlserializable-in-readonly-structs/)) but that's tricky, as it contains a reference type.
We can't take the address of `this`, and although we can take the address of the `offsetDateTime` field, we can't take the address of `zone`.

I could make `ZonedDateTime` a non-readonly struct, but it's the struct that benefits the most from it. Hmph.

**Comment by mgravell** [comment]
The 4.0.4.0 is because nuget and assembly versions don't match on netfx - it causes no ends of confusion, but it isn't actually a huge problem in itself.

SRCSU is one of the group of horribly horribly broken ones that can cause huge assembly binding redirect problems, although this largely goes away from net472 onways, and goes away completely in .NET Core. I was *going* to say "if your type doesn't include ref-types, you can cheat with 'unsafe' and 'fixed', and avoid the package dependency", but I see that you've already covered that in the 2018 post. Honestly, there's no simple wins here, and the assembly binding thing is just *pure pain*, because the tooling does not, can not, and will not - generate the right things. This is just one more in a long series of things that makes me suggest that you seriously consider, if you're bumping a major *anyway*, changing the TFM to ns2.1 (or netcoreapp3.anything). The key thing here being: netfx and assembly binding redirect problems just *go away*. I realize this is a huge and slightly political decision, and I also hold my hands up and admit that I haven't pulled that handle myself yet, but... the time will come when it is necessary: https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html 

Nick's post here may also be useful: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by mgravell** [comment]
Btw, if you're open to ref-emit, you can write a 2-op-code (IIRC) method at runtime (`DynamicMethod`) that does the same as `static ref T AsRef<T>(in T val)` - pretty sure it is just `ldarg.0`, `ret`

**Comment by jskeet** [comment]
@mgravell: Thanks for this. Yup, I read that blog post when it was posted - that's why I thought of you :)

I don't think I'm ready to do that with Noda Time. I think that not supporting either .NET Framework *or* netcoreapp2.1 isn't feasible just yet. It's possible that Noda Time 4.x, if that ever happens, will target netstandard2.1 (or maybe even a later version).
In terms of the "getting assembly binding redirects right" - is there a page with a good explanation of this that I could reference in documentation? I think I'm prepared to say "If you're using .NET Framework, expect a bit of pain, but here's how you can fix it."

I don't think I want to do ref emit, but I do wonder whether I could do something else - create my own `AsRef` method which does nothing in the "normal" IL, but then as a post-build step, replaces the IL with the "real" IL. Does that sound feasible?

**Comment by mgravell** [comment]
Yes, that is very feasible. It is how a lot of the fxcorelabs stuff worked when span was pre-release. You might also be able to use an ilproj - I think I'm remembering that as "a thing".

**Comment by jskeet** [comment]
@mgravell: Mmm. I think if this were earlier in the cycle, I'd look into that further. Thinking about trying to make sure the resources, PDBs etc are still valid this close to a 3.0 makes me very nervous.

Given that this will only be a problem for .NET Framework projects which also use XML deserialization, I think I'll probably stick with "the devil I know" (albeit not terribly well) - but update the dependency.

Thanks for all the feedback.

**Comment by jskeet** [comment]
@malcolmr: Let's work out how to document this. It looks like with assembly binding redirects, the binary compatibility is better than I'd actually expected.

**Comment by malcolmr** [comment]
So, I don't pretend to fully understand this (and in particular as to whether #1537 has any bearing  here), but based on the above, if we know that it's feasible, I think it's sufficient to just add a pointer for now.

For example, we could add a short paragraph to the end of the introduction in https://nodatime.org/unstable/userguide/migration-to-3 similar to:

> ... we intend for Noda Time 3.0 to be both source- and binary-compatible with Noda Time 2.x. 
> 
> Note that making use of binary compatibility to upgrade an existing deployment without recompiling will require adding appropriate assembly binding redirects so that the new library can be loaded in place of the old (and also requires running on a platform version supported by Noda Time 3.0).

(The last bit seems obvious to me, but it's probably worth clarifying that this (presumably?) won't work if you're running an application using .NET Framework 4.5.)

We can expand that later on if anyone actually asks for more details.

It wasn't clear to me from the above whether you managed to get XML deserialization to work. If not, perhaps append "Additionally, applications making use of XML deserialization in Noda Time 2.x cannot [currently?] make use of this, and must be updated to use Noda Time 3.0 explicitly." (or whatever words make sense here).

**Comment by jskeet** [comment]
Sorry, yes, I hadn't included the result of that - yes, I was able to get XML deserialization using this assembly binding redirect config:

```xml
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NodaTime" publicKeyToken="4226afe0d9b296d1" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-2.4.8.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

(That was before I updated the dependency in NodaTime.dll itself - so this isn't the exact configuration we should tell people about, but it'll be similar.)

**Comment by jskeet** [comment]
I'm releasing 3.0 despite this still being open - we want to add some more documentation around this, but it can wait until after the release.

**Comment by malcolmr** [comment]
I've added the paragraph I quoted above directly to the migration guide, which should be enough for now.

If we want to provide more information ("appropriate assembly binding redirects" is calling out for a link to something useful :)), we can do at a later date.

**Comment by jskeet** [comment]
Closing as I think we're probably fine.
