### ISSUE TITLE
ZonedDateTime to ToUnixTimeSeconds

### ISSUE THREAD

**Issue by goforgold** [nodatime/nodatime#1534]
Hi @jskeet and team!

Thanks for doing this wonderful library for .NET developers. I recently moved my trading system from .NET DateTime APIs to NodaTime because of lack of features and consistency in .NET DateTime APIs.

I am mostly storing times in Unix Epoch Seconds inside different structures and I frequently convert UTC to Local and vice-versa at different places in my project.

[This ](https://nodatime.org/2.2.x/userguide/arithmetic)document describes (quoting):

> The Instant and ZonedDateTime types both unambiguously refer to a point in time (with the latter additionally holding time zone and calendar information). 

I can instantly convert from an object of `Instant` to Unix Epoch Seconds using `ToUnixTimeSeconds()` method. Really that is very fast (below are some very basic test results).

Since there is no direct way to convert `ZonedDateTime` object to Unix Epoch Seconds. I am doing `zoned.ToInstant().ToUnixTimeSeconds()`. That is a bit slow.

I am required to it on average 100 million times for running simulations. **I was hoping if there is any faster way to get Unix Epoch Seconds from `ZonedDateTime` object to Instant**.

Below is how I am testing it. I am not sure this would qualify as the standard test, I just did this for my own testing.

```C#
LocalDateTime local = new LocalDateTime().PlusSeconds(86400);
ZonedDateTime zoned = local.InZoneStrictly(DateTimeZoneProviders.Tzdb["America/New_York"]);
Instant instant = zoned.ToInstant();

DateTime now = DateTime.Now;

for (int i = 0; i < 100000000; i++)
{
  instant.ToUnixTimeSeconds();
}

Console.WriteLine("Instant: " + (DateTime.Now - now).TotalSeconds);

now = DateTime.Now;

for (int i = 0; i < 100000000; i++)
{
  zoned.ToInstant().ToUnixTimeSeconds();
}

Console.WriteLine("Zoned: " + (DateTime.Now - now).TotalSeconds);
```

Output:
```
Instant: 0.2982887
Zoned: 2.9066556
```

**Comment by jskeet** [comment]
I can have a look at exactly what path this is taking and try to optimize it, but the path you're taking is the correct one.

We do already have a [benchmark](https://github.com/nodatime/nodatime/blob/master/src/NodaTime.Benchmarks/NodaTimeTests/PacificZonedDateTimeBenchmarks.cs#L46) for this.

The [most recent results](https://nodatime.org/benchmarks/types/1ad1d1a8-bfe7-41f3-951c-00324b9e25e2) suggest that `ToInstant()` takes about 24ns in my benchmark. That's about what you're seeing too - and what I see on my machine. That's surprising to me, given that the benchmark machine is a lot slower than my laptop.

I'll dig in a little further, but given that it *does* need to do a conversion from the local parts (year, month day etc) to an instant in time, I'm not sure that we're likely to get it much faster than the 20-30ns we're seeing.

**Comment by goforgold** [comment]
Thanks @jskeet for looking into this case.

If you believe that we are not going to get some interesting performance increase here a conversion is required here. Do you think that there could be some possible workaround which I can do in my program to get Unix Seconds from an instance of `ZonedDateTime` considerably faster?

> I'll dig in a little further, but given that it does need to do a conversion from the local parts (year, month day etc) to an instant in time, I'm not sure that we're likely to get it much faster than the 20-30ns we're seeing.

**Comment by jskeet** [comment]
Not considerably faster, no. I believe the bottleneck is very likely to be the "date to number of days since epoch" conversion. I'll need to do some more benchmarking to validate that expectation (and that benchmarking will help optimize where we can) but I suspect that ~30ns is about as quick as you should expect that to happen.

If you're doing this for a lot of values that are in a short amount of time, you *may* be able to come up with some kind of caching mechanism, but it would be quite fiddly. (We already have a cache within Noda Time for this to some extent, but yours could be more tuned to your specific needs.)

**Comment by jskeet** [comment]
Okay, running `ToInstant().ToUnixTimeSeconds()` in a benchmark takes ~20ns.

I've managed to create a more direct path which reduces this to 10ns, of which I believe 6ns is `LocalDate.DaysSinceEpoch`, and I'd be surprised if we can squeeze that harder.

Now, a 2x throughput improvement is now - but I really don't want to add `ZonedDateTime.ToUnixTimeSeconds()`. If this improvement is sufficiently dramatic to be interesting to you, I can try to work something which *is* reasonable but which doesn't feel like an API abuse. If you were looking for something more like a 5-10x improvement and a 2x improvement doesn't help, I won't bother looking - because I don't think that's feasible.

**Comment by goforgold** [comment]
Hi @jskeet 

2x performance will be really great if you think it is achievable. That is sure going to speed up my simulations by up to 10 seconds which would really a drastic improvement.

I really don't mind calling `ZonedDateTime.ToInstant().ToUnixTimeSeconds()`. Initially, I was thinking that maybe you have something internally stored in `ZonedDateTime` which could lead to a direct translation.

Now, I will shamelessly ask for your help in some coding related to this topic. Please let me know if you think I could do it in a more performant way. I have a `DateTimeOffset` (actually it is just date part with 0 offset) coming from another library. My requirement is to remove the time component from the `DateTimeOffset` object. Give it a fixed time in a day and get back the Unix Seconds.

```C#
TimeSpan sessionCloseTs = sessionInfo.Sessions[barTime.DayOfWeek].Close; // barTime is .NET DateTimeOffset
LocalDateTime closeLocal = new LocalDateTime(barTime.Year, barTime.Month, barTime.Day, 0, 0).PlusSeconds((long)sessionCloseTs.TotalSeconds);
ZonedDateTime closeZoned = closeLocal.InZoneStrictly(sessionInfo.IanaTimeZone); // sessionInfo.IanaTimeZone is `DateTimeZone`
return closeZoned.ToInstant().ToUnixTimeSeconds();
```

**Comment by jskeet** [comment]
Ah, that's really interesting. If that's *all* you need to do, there may be a significantly faster way of doing it. Will experiment.

**Comment by jskeet** [comment]
Okay, it looks like the bottleneck really isn't `ToUnixTimeSeconds` - it's the way the rest of it is done.

You can at least make the code *simpler* (but without gaining much performance) like this (where `Pacific` is the time zone I'm using in the benchmarks):

```csharp
DateTimeOffset dateAndTime = barTime - barTime.TimeOfDay + sessionCloseTs;
LocalDateTime closeLocal = OffsetDateTime.FromDateTimeOffset(dateAndTime).LocalDateTime;
ZonedDateTime closeZoned = closeLocal.InZoneStrictly(Pacific);
return closeZoned.ToInstant().ToUnixTimeSeconds();
```

But here's code which massively improves the performance, at the cost of some complexity:

```csharp
DateTimeOffset dateAndTime = barTime - barTime.TimeOfDay + sessionCloseTs;
// This isn't really an instant in time - but our DateTimeOffset isn't either.
// It's handy though, as it allows us to do all the working without calendrical
// calculations, unless we're near a time zone transition.
Instant localInstant = Instant.FromDateTimeOffset(dateAndTime);
// Work out the offset as if our "local instant" was the real instant. We expect it
// to be close, after all.
var candidateOffset = Pacific.GetUtcOffset(localInstant);

// Now work out the real instant by subtracting the offset that would be correct at the
// "local instant".
Instant result = localInstant.PlusTicks(-candidateOffset.Ticks);

// If the UTC offset at the real instant is the same as the one we calculated
// for the "local instant", we assume there are no transitions between the two, and we're
// done.
if (Pacific.GetUtcOffset(result) == candidateOffset)
{
    return result.ToUnixTimeSeconds();
}
else
{
    LocalDateTime closeLocal = OffsetDateTime.FromDateTimeOffset(dateAndTime).LocalDateTime;
    ZonedDateTime closeZoned = closeLocal.InZoneStrictly(Pacific);
    return closeZoned.ToInstant().ToUnixTimeSeconds();
}
```

That basically relies on what I know to be fast in Noda Time:

- Converting a `DateTimeOffset` or `DateTime` into an instant
- Performing simple duration-based arithmetic on instants
- Computing the UTC offset from an instant

This doesn't involve any calendar arithmetic unless you happen to hit an area in the time zone which isn't in its local cache yet.

Now it's somewhat unpleasant code, in terms of saying "Let's guess what the offset might be, then check whether or not we're right." That's actually pretty close to what [DateTimeZone does internally](https://github.com/nodatime/nodatime/blob/72f86bbdb6543012032fcb3181f11749a81830d5/src/NodaTime/DateTimeZone.cs#L238). I'm confident in it as an approach, although I hope you've got some appropriate tests - I've benchmarked this for *speed*, but haven't tested it for *correctness* :)

The performance is very pleasant though. Running the benchmarks, I get results of:

- Your original code: 202ns
- The simplified code: 198ns
- The fast code: 74ns

As a reminder, the improvement of just `ToUnixTimeSeconds` was shaving ~10ns off.

Of course, if you actually need the `ZonedDateTime` for other reasons you haven't shown, this may not quite work for you. Please let me know.

**Comment by goforgold** [comment]
Thanks @jskeet 

It is impressive!

My Unit tests are reporting good with these changes. I am just not understanding when this transition is happening. If/Else part. Is this in relation to DST? Is yes then how.

For example, I am using "America/New_York" as time zone where DST starts at `8-Mar-2020 02:00` (+1). I made below observations:

If I set `barTime` as:
```Cs
DateTimeOffset barTime = new DateTimeOffset(2020, 3, 8, 0, 0, 0, TimeSpan.Zero);
```
1. Then it gets inside `if` block when `sessionCloseTs` is (hh:mm:ss):
  `<= 01:59:59`

2. And it gets inside `else` block when `sessionCloseTs` is (hh:mm:ss):
  `>= 03:00:00 AND <= 06:59:59`

3. It gets back to `if` block when `sessionCloseTs` is (hh:mm:ss):
  `>= 07:00:00`

Although it does produce correct results, I am just not understanding the condition here. How does it relate to DST transitions?

`Of course, if you actually need the ZonedDateTime for other reasons you haven't shown, this may not quite work for you. Please let me know.`

No, I do need `ZonedDateTime` for other reasons.

**Comment by jskeet** [comment]
> How does it relate to DST transitions?

Fundamentally, we're trying to convert a local time (e.g. Pacific) to UTC. For that, we need the UTC offset at that UTC instant in time.

The `localInstant` variable is an instant in time representing the incoming local date/time, but interpreting it as if it were already in UTC.
The code works out the UTC offset in the given time zone at *that* instant, then subtracts that offset to make a first guess at the *real* instant in time we want to represent. That will be correct so long as there aren't any time zone transitions between our slightly odd "local instant" and the candidate instant. That's why we fetch the UTC offset again, and check that it's what we expected it to be. If it isn't we must be somewhere around a time zone transition (usually but not always DST transition), so we take the slower path, letting Noda Time do the heavy lifting.

I apologise that the description is a little confusing - it's because we "kind-of" abusing the Instant type, but in a well-defined way.

It's possible that calling `GetZoneInterval()` once and then checking that the zone interval contains `result` would be faster than calling `GetUtcOffset()` twice, but I suspect it would be marginal at best.

**Comment by goforgold** [comment]
Thanks @jskeet 

I think I am understanding it now.

> I've managed to create a more direct path which reduces this to 10ns, of which I believe 6ns is LocalDate.DaysSinceEpoch, and I'd be surprised if we can squeeze that harder.

Have you committed those changes already?

**Comment by jskeet** [comment]
No. Given that it would make relatively little difference compared with the application-side changes, I'd rather not do those.

**Comment by goforgold** [comment]
Thanks @jskeet once again for helping me out.

You are really a wonderful person.

I think we can close this issue now.
