### ISSUE TITLE
Question/Suggestion: Support For Frame Based Times

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [nodatime/nodatime#1565]
When working with tv or video, we need to represent times as x frames per second, where in the uk x would equal 25 but in the us it might be 60.

I have created my own version of DateTime where I use the millisecond component to store my frames per second but I do all the calculations myself.

This works ok but I have started to hit issues with time zones and trying to get the standard classes to accurately tell me if a TZ converted datetime is in daylight savings or not. This seems fundamentally broken in that the standard classes assume dates and conversions are local to the pc clock rather than in a specific time zone. So my test suite works on my pc, but when the CI system builds and tests, things fail because the system clock is in UTC.

I am thinking of using NodaTine instead as I have read that dates/times are referenced as a point of time 'in' a time zone (when using ZonedDateTime) which seems more correct/accurate, and I will need to wrap it to provide my own handling/arithmetic to support my FPS needs.

So I ask, before I embark on this difficult journey, is this capability something that may be incorporated into NodaTime, or is it  specific a requirement?

**Comment by jskeet** [comment]
Okay, several comments to make here.

Firstly, I would suggest you reconsider using the millisecond value to represent something that isn't actually milliseconds. With your current approach, you end up with a `DateTime` (or a Noda Time type) that isn't really what it claims to be - and where various operations that are generally valid with the type become inappropriate. I would instead suggest encapsulating the value in a new struct which includes a `DateTime` (or whatever), a frame number within the second, and a frame rate. (While you *could* omit the frame rate, it makes it a lot easier to spot incorrect usages if it's there.)

Secondly, it doesn't sound like you really *need* to move to Noda Time - you just need to use the BCL more appropriately. Yes, if you use `DateTime.ToLocalTime` and `DateTime.ToUniversalTime` to perform time zone conversions, that will use the system local time zone. I don't like that decision either - but you can work around it by simply not using those methods. Instead, use `TimeZoneInfo` to control the time zone conversions. Personally I still prefer various aspects of the way that Noda Time handles things (of course) but I'd be surprised if you really *couldn't* do what you need using `TimeZoneInfo`.

Thirdly, I definitely wouldn't be adding video frame rate support to Noda Time. It wouldn't be unreasonable for there to be a separate library to do that based on Noda Time, if there's a significant demand, but I wouldn't want it to be part of the core library. You might want to consider that possibility as a potential future goal when writing your own code: separate out "all the date/time parts" from the rest of your code with a clear boundary, so that if you then hear of other projects that would benefit from it, it could be spun out as a separate library.

I'll close this issue now as I don't believe there's any change to Noda Time required, but best of luck.
