### ISSUE TITLE
Confusing behavior when parsing strings

### ISSUE THREAD

**Issue by aivarasgg** [nodatime/nodatime#1586]
There is some confusing behavior with date parsing (in this particular case `NodaTime.LocalDateTime`), I would like to double check if this is an expected behavior or an issue.

I created this test:
``` c#
[Test]
[TestCase("en-GB")]
[TestCase("en-US")]
[TestCase("de-DE")]
[TestCase("nb-NO")]
public void LocalDateTimeParsingTests(string culture)
{
     var parser = LocalDateTimePattern.Create("dd/MM/yyyy HH:mm:ss", CultureInfo.GetCultureInfo(culture));
     var result = parser.Parse("20/01/2020 15:36:04");
     Assert.AreEqual(new LocalDateTime(2020, 1, 20, 15, 36, 4), result.Value);
}
```
It fails on "de-DE" and "nb-NO" cultures, the other two succeed. Error message is:
`NodaTime.Text.UnparsableValueException : The value string does not match a date separator in the format string. Value being parsed: '20^/01/2020 15:36:04'. (^ indicates error position.)`

 What is confusing about it is that the property `parser.PatternText` shows the pattern which was specified in `LocalDateTimePatter.Create`, but it seems like under the hood it is using format from specific culture, not the one which was specified.

If the pattern is created using `CultureInfo.InvariantCulture` everything seems to work as expected, even if threads have different cultures.

**Comment by malcolmr** [comment]
I'm almost certain this is the intended behaviour: `/` in a custom format string matches the date separator _for the format provider_, which may or may not be a literal `/` character. Same goes for the `:`, for that matter.

If you _do_ want to require a literal `/` or `:` in an otherwise culture-sensitive pattern, you should be able to use a quoted version, with single or double quotes, resulting in a pattern like `"dd'/'MM'/'yyyy"`.

(Though in this particular case, it would probably be simpler just to use the invariant culture. That _does_ always use `/` and `:` respectively.)

For more, see https://nodatime.org/userguide/localdate-patterns and https://nodatime.org/userguide/text#custom-patterns.

**Comment by jskeet** [comment]
Exactly. For en-GB and en-US, the date separator is `/`. For de-DE and nb-NO it's `.`.

This is working as intended.
