### ISSUE TITLE
Noda json DateTime conversions

### ISSUE THREAD

**Issue by jtleaming** [nodatime/nodatime#1623]
When I make a HTTP request to another service, which returns JSON with a DateTime, the DateTime string is not parsed into the correct Noda type. I realize the JSON serializers are meant to convert Noda types to and from JSON, however it would be very useful if they could also handle converting a DateTime json value (more or less a string of "2021-12-12T00:00:00-03:00") into the expected Noda type.

**Comment by jskeet** [comment]
I'm afraid I'm finding it very hard to understand this issue. What does your code look like? How are you configuring the serializer? If the types are right and the serializer is properly configured, it should all just work.

**Comment by jtleaming** [comment]
This is the basis of what I am trying to do. 
I would have thought the dates in the json string would have been converted to the Noda types, but I get a serialization error when trying to do this.
``` C#
public class DateTimeJsonConverterTests
    {
        private JsonSerializerOptions jsonSerializerOptions = new()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true
        };

        public record TestObject(LocalDate Date, LocalTime Time, LocalDateTime DateTime);

        [Fact(DisplayName = "Converts DateTime Types to Noda types")]
        public void ConvertDateTime()
        {
            jsonSerializerOptions.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

            var jsonString =
                @"{ ""date"": ""2020-10-15T00:00:00-06:00"", ""time"":""2020-10-15T08:00:00-06:00"",""dateTime"": ""2020-10-15T15:00:00-06:00""}";

            var result = JsonSerializer.Deserialize<TestObject>(jsonString, jsonSerializerOptions);

            result.Date.Should().Be(new LocalDate(2020, 10, 15));
            result.Time.Should().Be(new LocalTime(8, 0, 0));
            result.DateTime.Should().Be(new LocalDateTime(2020, 10, 15, 15, 0, 0));
        }
    }
```

Similarly this doesn't work in my ASP code

```C#
// OTHER Startup code...
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
            });
           //.....et cetra....
        }
```

```C#
//OTHER controller code and whatnot
        public record LineItem(LocalDate date);
        [HttpGet("{from}/{to}")]
        public async Task<IActionResult> GetDate(DateTime from, DateTime to)
        {
            var response = await client
                .GetFromJsonAsync<LineItem>($"api/v1/date/{from:O}/{to:O}");
            return new OkObjectResult(response);
        }
```
I am calling another service I control, so I know the date in the response is actually a DateTime object.

**Comment by jtleaming** [comment]
Also might be worth noting I am using `NodaTime.Serialization.SystemTextJson` and similarly using .net's SystemTextJson for json conversion. I think it just comes standard as part of `GetFromJsonAsync<>`.

**Comment by jskeet** [comment]
Okay, two problems here:

- Your JSON doesn't match the types you're trying to deserialize to in your test. `"2020-10-15T00:00:00-06:00"` isn't a JSON representation of a `LocalDate`, or a `LocalTime`, or a `LocalDateTime`. It's an `OffsetDateTime`.
- Your ASP.NET Core code doesn't use Noda Time types at all, so I don't know how you'd expect Noda Time to be involved. You'd need to have parameters which are Noda Time types for the serializers to be invoked

**Comment by jtleaming** [comment]
Correct those are not Noda types and that is my exact point here. On the server side the type is a System.DateTime. The System.DateTime gets converted into the json string above. It would be nice if a client doesn't have to worry about the type on the response message, but could generically convert DateTime objects to the anticipated Noda types. 

On a daily basis my services interact with .net servers which are sending DateTimes in their responses. I would like to be able to use Noda time in my own services, but the json conversion doesn't work. It makes sense clients using Noda should be able to handle json conversion of DateTimes to their desired Noda time.

The Noda type being used is in the record declared above GetDate `public record LineItem(LocalDate date);`. So, not on the request itself, but the response is returning a DateTime but I want it to be a LocalDate.

This seems possible to do, and I am working on writing my own json converters to handle this case. But it also seems like a useful feature out of the box. Not all Clients can be assured the date/times they are getting back will be formatted as the anticipated Noda type. So long as it is a DateTime format the conversion should work.

**Comment by jskeet** [comment]
>  It would be nice if a client doesn't have to worry about the type on the response message, but could generically convert DateTime objects to the anticipated Noda types.

There aren't DateTime objects in the JSON though. There are just string values.

> So, not on the request itself, but the response is returning a DateTime but I want it to be a LocalDate.

Then you should add a conversion in yourself: have a response type which is appropriate to the data in the JSON, then convert that to the type that you want the rest of your code to deal with. That makes it really, really clear what you expect the JSON to look like, and that you're *deliberately* losing information in the conversion. 

> So long as it is a DateTime format the conversion should work.

I disagree. Expecting an OffsetDateTime value to be converted silently to LocalDate is like expecting 10.5 to converted to an `int`... if my code loses information, I want to be alerted to that really clearly, because it's *almost* always a mistake.

If you want to introduce your own converters that silently lose information, that's up to you - but I don't want to put them into Noda Time.

I'll close this issue now, as I don't believe we'll want to make any changes based on it.

**Comment by jtleaming** [comment]
I know you closed this, but I still think this is worthwhile. Here's why....

> There aren't DateTime objects in the JSON though. (There are no such things.) There are just string values. You can convert those to the appropriate Noda Time types, but not to ones that don't match the values you've given.

Technically true, these are just strings. But .net's JSON serializers will convert these strings to DateTime objects and vice versa. Similarly, joda libraries will do this in javascript. My point being, while in JSON these are strings, many languages interpret this string as some type of date object.

>Then you should add a conversion in yourself....

Yup, which is likely what I'll be doing. But the entire point is how common it is for .net services to send DateTime objects in their reponse messages; yes, as a serialized strings. But .net, and even the js joda librarly, will interpret these strings as some type of date object.

>I disagree. Expecting an OffsetDateTime value to be converted silently to LocalDate is like expecting 10.5 to converted to an int... if my code loses information, I want to be alerted to that really clearly, because it's almost always a mistake.

I think it is inaccurate to compare DateTime/OffsetDateTime to int. Ints are primitive types where are DateTimes are a struct, and I don't see ignoring data in certain cases as losing information. Let's pretend for a moment .net doesn't serialize DateTimes as strings, but rather  as a JSON objects. A date of 2021-12-20T08:10:00 might end up looking something like this...
```
{
year: 2021,
month: 12,
day: 20,
hour: 8,
minute: 10,
second: 0
}
```
It wouldn't be uncommon for my client to parse this JSON response to an object like this...
```
{
year: 2021,
month: 12,
day: 20
}
```

I don't think this is unreasonable or uncommon a case.

**Comment by jskeet** [comment]
> I don't see ignoring data in certain cases as losing information

When you start with a date, time and offset, but end up with just a date, that *is* losing information.

If you start with two values in the JSON, one "2021-12-12T00:00:00-03:00" and the other "2021-12-12T08:30:00-05:00", but you convert them both into just `LocalDate`, you then can't get back to the original values. That's pretty much the definition of losing information - just like converting 10.5 into the integer 10 loses information. (And I think the "`int` is a primitive" part is a complete red herring. We're talking about overall information strategies, not language specifics.)

A large part of Noda Time's philosophy is that you need to think about your data and express it precisely - that's why there are so many types in Noda Time compared with basically `DateTime` and `DateTimeOffset` in the BCL. If you want a system where you don't want to particularly tell the difference between "a date/time where the time is midnight" and "a date", then Noda Time probably isn't the right library for you. But I'm not going to change the way the JSON converters work to start implicitly losing data - if you want to use Noda Time but go against its philosophy, you'll need to do that in your own converters.
