### ISSUE TITLE
ToString on Empty Period does not follow ISO8601 returns 'P'

### ISSUE THREAD

**Issue by mennolodder** [nodatime/nodatime#1629]
When doing ToString on a zero period (happen on both lines in the unittest below), I get `'P'` as the result. This is not valid ISO8601, as this requires a zero period to have at least a single field given, such as `'P0S'`, of `'P0D'`. This also seems to contradict the behavior described in ticket #46.

```
        [Test]
        public void DurationToString()
        {
            Assert.AreEqual("P0S", Period.FromSeconds(0).ToString(), "Period 0 seconds"); // Actually is 'P'
            Assert.AreEqual("P0S", Period.Zero.ToString(), "Period without fields"); // Actually is 'P'
        }
```

Note that we run into empty Periods when storing a 0 period in our postgresql database, and retrieve it using the NodaTime type mapping in entity framework these periods then get serialized to JSON using  `NodaTime.Serialization.SystemTextJson`. 

Tested using nodatime 3.0.5

**Comment by jskeet** [comment]
Good catch - thanks. It should be fairly easy to fix... I've been thinking of creating a 3.1.0 release anyway, so it could go into that. I do wonder whether it's worth backporting to 3.0.x and 2.4.x though...

**Comment by mennolodder** [comment]
Thanks for your quick reply. 

As for needing a backport: I was quiet surprised I couldn't find others with this issue. The jsjoda duration parse function doesn't accept a 'P' value for zero. Which is how we found it.

**Comment by jskeet** [comment]
Yup, I'm surprised this is the first I've heard of it, too :)

Just thinking about it further, in 3.1 I may make it configurable between "P0D" and "P0S", whereas I can't do that in the backports as it wouldn't be forward-compatible in that case.

**Comment by mennolodder** [comment]
Depens on if people are interested in configuration. For me P0S seems more natural (seconds are easier, so a safer bet as default), and seconds are the SI unit. But it doesn't seem to matter very much. I think it only matters when people use very basic custom parsing (which would already need to make an exception to support 'P' as zero).

**Comment by jskeet** [comment]
Looking into this, it seems the "normalising ISO" pattern already uses "P0D". It's only the round-trip pattern (which is used by `Period.ToString`) that fails. The use of "P0D" is unfortunate as after considering it a bit, I think I'd prefer "P0S" as well, but I don't want to change behaviour of any already-working code. I'll make both use "P0D" for now, and consider making it configurable in the future.

For backward compatibility, I think I probably need to make the normalising pattern accept just "P" - otherwise anyone trying to parse a value they've previously formatted will run into problems. It's one of those situations where there's no good solution, unfortunately... but I'll do what I can.
