### ISSUE TITLE
Support conversion to/from DateOnly and TimeOnly

### ISSUE THREAD

**Issue by mattjohnsonpint** [nodatime/nodatime#1635]
.NET 6 Preview 4 added `DateOnly` and `TimeOnly` structs.  I would like to propose that Noda Time should support two-way conversion between `DateOnly` and `LocalDate`, and between `TimeOnly` and `LocalTime`.

```csharp
public struct LocalDate
{
    public static LocalDate FromDateOnly(DateOnly date);
    public static LocalDate FromDateOnly(DateOnly date, CalendarSystem calendar);
    public DateOnly ToDateOnly();
}

public struct LocalTime
{
    public static LocalTime FromTimeOnly(TimeOnly time);
    public TimeOnly ToTimeOnly();
}
```

**Comment by jskeet** [comment]
Hmm. I'm definitely very happy with this in principle... I do feel we took a positive step in dropping all our conditional logic back in 3.0 to target just netstandard2.0. Presumably this would add a target of net60.

One *option* would be to have a separate package just for this. Not sure that helps much either though. I can probably live with the multi-targeting if we have to... it does feel like a useful thing to have.

**Comment by malcolmr** [comment]
Seems reasonable to me in general, but would there be a way of doing this without making the NodaTime library .NET 6-only?

- The conversion from `LocalTime` to `TimeOnly` would be slightly lossy (`LocalTime` has nanosecond resolution; AIUI `TimeOnly` has 100ns resolution, presumably we'd just round down).

- `DateOnly` is a bit more complex. To start, I can't tell whether it can represent years prior to 1 CE, but if not, then there are some `LocalDate` in the ISO/Gregorian calendar that wouldn't convert (we support back to 9999 BCE, IIRC).

- It's also not obvious to me whether `DateOnly` assumes any particular calendar. I'm _guessing_ it just wants numbers that fit into a perpetual Gregorian calendar, which makes me wonder whether the conversion should just attempt to make a `DateOnly` with matching day/month/year (even though that probably wouldn't make too much sense for non-Gregorian calendars, and might even fail for e.g. some dates in the Hebrew calendar), or whether it should have an implicit `.WithCalendar(CalendarSystem.Iso)` first (which could also fail in some cases, of course).

- If we did the latter, we _wouldn't_ want a `FromDateOnly(DateOnly, CalendarSystem)` overload, since we'd effectively be asserting that `DateOnly` = ISO calendar... though similar arguments also apply to `DateTime`, and I see that we _do_ have `LocalDate.FromDateTime(DateTime, CalendarSystem)`.

**Comment by mattjohnsonpint** [comment]
`DateOnly` is like `DateTime` in its calendaring.  It's strictly Proleptic Gregorian and ranges from `0001-01-01` to `9999-12-31`.  The constructor on `DateOnly` that accepts a `Calendar` is only used if to translate the year, month, and day values in that calendar to Gregorian - it's then discarded.  Since there's already an overload of `LocalDate.FromDateTime` that takes a calendar system, I propose these should use the same behavior as that.

**Comment by mattjohnsonpint** [comment]
`TimeOnly` is easier, as it's essentially just `LocalTime.FromTicksSinceMidnight(timeOnly.Ticks)` and `new TimeOnly(localTime.TickOfDay)`.  But yes, it is lossy in the second case.

**Comment by mattjohnsonpint** [comment]
> I can probably live with the multi-targeting if we have to...

I think that's the right move.

**Comment by 0xced** [comment]
I already have started experimenting with adding a `net6.0` target, you can have a look at my [net6.0-DateOnly-TimeOnly](https://github.com/0xced/nodatime/tree/net6.0-DateOnly-TimeOnly) branch.

Currently, I have added the .NET 6.0 target framework and fixed all the nullability warnings that ensued. And in my last commit, I just implemented `public static LocalDate FromDateOnly(DateOnly date)` and an extension method on `DateOnly`: `public static LocalDate ToLocalDate(this DateOnly date) => LocalDate.FromDateOnly(date);`

Now, some tests are failing on .NET 6.0 but that should probably be tracked in another issue since it's completely unrelated to the new `DateOnly` and `TimeOnly` types.
