### ISSUE TITLE
South Sudan Standard Time

### ISSUE THREAD

**Issue by ivan-prodanov** [nodatime/nodatime#1669]
I'm not really sure but to me it seems like a recent update of Windows 10 added the following time zone: "(UTC+2) Juba". When I try to convert this timezone to IANA format, it fails and cannot find it. Here's the code:

    
```cs
public static string GetIanaTimeZoneFromWindowsTimeZoneId(this string windowsTimeZoneId)
{
    var mappings = TzdbDateTimeZoneSource.Default.WindowsMapping.MapZones;
    var ianaTimeZone = mappings.FirstOrDefault(x => x.WindowsId == windowsTimeZoneId)?.TzdbIds.FirstOrDefault();

    return ianaTimeZone;
}
```

Invoked with 

```cs
TimeZoneInfo.Local.Id.GetIanaTimeZoneFromWindowsTimeZoneId()
```

It does not work when the windowsTimeZoneId is "South Sudan Standard Time" which in windows 10 appears as "(UTC+2) Juba"

**Comment by jskeet** [comment]
This is because all the releases so far have used CLDR v39 or earlier. The latest release of NodaTime was on 2021-10-22, and we didn't add the CLDR v40 data file until 2021-10-29.

I don't generally do releases just for CLDR updates - so I suggest you add a workaround (just hard code a mapping to "Africa/Juba") until the next release (which is likely to be due to the next IANA release).

**Comment by ivan-prodanov** [comment]
Thanks! That's what I did as a quick workaround. Could you please link this issue to the next release so I can get a notification to remove the dirty fix when the time comes and issue is closed?

**Comment by jskeet** [comment]
I'll *try* to remember, to do so, but I don't guarantee... (We don't have any infrastructure to do that automatically.)

**Comment by jskeet** [comment]
Closing - with Noda Time 3.0.10, this maps to "Africa/Juba".
