### ISSUE TITLE
Making certain LocalDate-based comparisons more discoverable

### ISSUE THREAD

**Issue by robertmclaws** [nodatime/nodatime#1703]
When a LocalDate exists on a property but has no set value, the value comes back on the property as "0001-01-01". LocalDate needs a static property called "Empty" equivalent to that value.

**Comment by malcolmr** [comment]
The default value of `LocalDate` isn't an invalid value, though, so defining that date to be semantically an "empty" value wouldn't be correct. (I also don't see any parallel in other types? There's no `DateTime.Empty`, for example.)

(Sidenote: we probably _should_ document the default value of each of our structs, since that's part of our API.)

Locally, you could presumably write `default(LocalDate)` (in C#, anyway) to get the default value, and if that means "empty" in your application, you can give it that name.

**Comment by jskeet** [comment]
Malcolm wrote exactly what I was going to write :) As well as `default(LocalDate)` you can use `new LocalDate()` which will give the default value too - although I'd personally use `default` as it's clearer.

And yes, we should document the default values. That should be a pretty simple PR - I'll try to do that today.

**Comment by robertmclaws** [comment]
Thanks for the quick response. My thought was to make it similar to how `System.Guid` has a static property called "Empty" that returns all zeros.

I was writing some code tonight, and I was looking for a `DateTime.MinValue` equivalent on `LocalDate`. I expected `LocalDate.MinIsoValue` to behave the same way, but it did not. On the plus side, I learned that the ISO standard's min value is negative, which is weird to me... but you folks know more about dates than I do.

Maybe a good alternative would be to have `LocalDate.MinValue` and `LocalDate.MaxValue` properties that mirror `DateTime`'s functionality, just without the time.

Appreciate you both!

**Comment by jskeet** [comment]
> Maybe a good alternative would be to have LocalDate.MinValue and LocalDate.MaxValue properties that mirror DateTime's functionality, just without the time.

`LocalDate.MinIsoValue` and `LocalDate.MaxIsoValue` return the min and max values expressible in Noda Time with the ISO calendar. It's deliberately specific to the ISO calendar, as a `LocalDate` "knows" its calendar system, which `DateTime` doesn't.

We *definitely, definitely* don't want to have `LocalDate.MinValue` returning 0001-01-01, as that's *not* a minimum value for a `LocalDate`.

We could *potentially* add `NodaConstants.BclEpochDate` and `NodaConstants.BclEpochDateTime` as `LocalDate` and `LocalDateTime` values.

Fundamentally, you need to decide what you're trying to represent - there are *three* different concepts in this issue already:

- The default value for `LocalDate`, which is obtainable via `default(LocalDate)`
- A value which matches `DateTime.MinValue` - that *happens* to be `default(LocalDate)`, but somewhat through luck
- The minimum value for `LocalDate`, which depends on the calendar system, but which is available for the ISO calendar via `LocalDate.MinIsoValue`

You really need to work out which of these is what you're interested in. From the first comment, it looks like you're interested in the default value, so I suggest you use the `default` operator.

**Comment by malcolmr** [comment]
(Small note: `Guid.Empty` exists because an all-zero UUID has a specific meaning: see https://en.wikipedia.org/wiki/Universally_unique_identifier#Nil_UUID.)

**Comment by robertmclaws** [comment]
Apologies for the confusion in trying to explain the process that got me here. 

**The first option solved my immediate problem, thank you.** And thank you for taking the time to be clear in your responses, it's not every day I get to converse with a couple of coding legends and learn a bunch of new stuff.

On the second part, please allow me to start fresh.

So earlier this morning I was updating a LocalDate-based algorithm that compared data that was coming out of a database as a `DateTimeOffset`, In making my comparison, I struggled to find an equivalent to the way developers commonly compare unset `DateTimeOffset` database values, by comparing against `DateTimeOffset.MinValue`.

After debugging through my unit tests to verify my work and seeing that `LocalDate.IsoMinValue` was not what I was looking for, I stumbled through the Immediate Window for 3-4 minutes checking values until I discovered that `new LocalDate()` got me what I was looking for.

Wouldn't it be cool if there was a static property on `LocalDate` and `LocalDateTime` that helped developers more intuitively discover the right way to do it through IntelliSense, vs fumbling through the tools or having to dig through the docs? It would have the same amount of discoverability that `Guid.Empty` or `DateTime.MinValue` does, and would help developers do the right thing.

Thanks again for your time, and for this fantastic library.

**Comment by jskeet** [comment]
> Wouldn't it be cool if there was a static property on LocalDate and LocalDateTime that helped developers more intuitively discover the right way to do it through IntelliSense, vs fumbling through the tools or having to dig through the docs?

Apply that logic to every situation ever encountered by a developer - and suddenly the LocalDate and LocalDateTime APIs have millions of members, and Intellisense takes 10 minutes to even load.

Fundamentally, using `default` is the right approach for *all* types, even `DateTimeOffset` - the developer doesn't really want to compare against the minimum value; they want to compare against "the default value for the type". Apply the same logic to all types, and there's no need for a new property anywhere, because the default operator works just fine. Note that if we applied the "there should be a property" approach to all types, then every *class* type would have a `Null` property which returned null (the default value for the type). I expect you wouldn't push for that, because you can just use `null` in the code... I encourage you to think of `default` as the equivalent for value types (although it also works for reference types, of course, returning a null reference).

**Comment by robertmclaws** [comment]
Ok cool. Thanks for your help, and hope you have a great week!
