### ISSUE TITLE
Consider adding Period.{Max,Min}Value

### ISSUE THREAD

**Issue by roji** [nodatime/nodatime#1807]
Similar to other NodaTime types.

The specific trigger here is PostgreSQL introducing `-infinity` and `infinity` to its `interval` type, which corresponds to Period (see https://github.com/npgsql/npgsql/issues/5696#issuecomment-2179805408).

**Comment by jskeet** [comment]
Other types are easily comparable though - `Period` does *not* implement `IComparable<Period>` or expose an `IComparer<Period>`. For example, which is longer: 30 days or 1 month?

**Comment by jskeet** [comment]
If it's DB-specific, I wonder whether it would make more sense for npgsql to implement an `IComparer<Period>` that follows the same rules as Postgres?

I'd misread the feature request though - I'd thought it was about adding `Period.Max(p1, p2)` etc. Just `Period.MaxValue` and `Period.MinValue` make more sense, although which units would be included would be another decision. (I see Postgres interval is only months/days/seconds, so would you want the `Period.MaxValue` to have those units?)

I'm happy to do something that makes sense, but I'll need more information before putting together anything. If you'd like to create a PR, that might be a simpler way forward (although I don't know when I'll get time for doing this regardless of how we do it).

**Comment by roji** [comment]
> If it's DB-specific, I wonder whether it would make more sense for npgsql to implement an IComparer<Period> that follows the same rules as Postgres?

Npgsql itself never actually does any sorting of values - all it does is convert .NET object (such as NodaTime Period) to the PostgreSQL encoding for the corresponding type (e.g. `interval`), and back; so we're not actually in needed of a Period comparer at all. The only actual need here is for the user to be able easily read and write infinity/-infinity values for PG interval. For Instant, for example, when the user tells Npgsql to send Instant.MaxValue, we send infinity (as "the value that's larger than all other values") - and here I'm proposing to do the same for Period

> Just Period.MaxValue and Period.MinValue make more sense, although which units would be included would be another decision. (I see Postgres interval is only months/days/seconds, so would you want the Period.MaxValue to have those units?)

Yep, this is really only about Period.{Max,Min}Value, nothing more.

PG interval goes up to years, and down to microseconds (all PG date/time-related types have a precision of 1 microsecond BTW. For example, [from the docs](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT):

```
SELECT '2 years 15 months 100 weeks 99 hours 123456789 milliseconds'::interval;
               interval
---------------------------------------
 3 years 3 mons 700 days 133:17:36.789
```

Just in case it's interesting, the actual internal representation of interval is months, days and microseconds (so Npgsql converts a NodaTime Period to these 3 values). For Period.MaxValue, I'd expect that to have MaxValue for all the individual components accessible on Period; Npgsql would simply compare the incoming Period instance to Period.MaxValue, and if that returns true, it would send an `infinity` interval to the database. Makes sense?

> I'm happy to do something that makes sense, but I'll need more information before putting together anything. If you'd like to create a PR, that might be a simpler way forward (although I don't know when I'll get time for doing this regardless of how we do it).

Sure - I'm also unlikely to have time to actually work on this any time soon... But if you generally think this makes sense, maybe I'd hack it at some point :) Or a contributor (@azan-n would you maybe be interested in this?)

**Comment by jskeet** [comment]
Right, that extra detail definitely helps. There are various things one couldn't usefully do with `Period.MaxValue`, such as call `ToDuration` - but that's already true of other period values. It sounds like they'd basically be values which *could* be constructed like any other, which should make the whole thing simpler to think about.

It sounds straightforward after all, and I'm okay to do it. It won't appear until we do a 3.2 release of course, which I'd been hoping to put off until I had time to look at time provider bits - but I wonder whether it's worth doing sooner rather than later, as we've started accumulating a number of features. (Admittedly https://nodatime.org/unstable/api/changes.html is slightly misleading as it's reporting `IXmlSerializable.GetSchema` as new for some reason, on a number of types.)

**Comment by roji** [comment]
Sounds good. @azan-n let us know if you're interested at taking a stab at this.

**Comment by jskeet** [comment]
> Sounds good. @azan-n let us know if you're interested at taking a stab at this.

Happy to review anything that comes soon, but I'll probably do it on Saturday otherwise (as I don't think it'll take more than an hour).

**Comment by malcolmr** [comment]
Just thinking through some of the designs discussed above (tl;dr: this seems fine):

One option (the one we've converged on, I think?) is to add `MinValue` and `MaxValue` values with some existing value (e.g. `new PeriodBuilder { Years = Int32.MinValue, Months = Int64.MinValue, ....}`), and then Postgres could use those for `-inf`/`+inf`. However, that's not a bijection, so you wouldn't be able to distinguish `+inf` from a real period with the same value (as you presumably can in Postgres). That's probably an acceptable limitation for this use case — it sounds like you've already decided that it's okay for `Instant`? — and this choice does mean that a lot of things (`ToString()`, `ToDuration()`, `ToBuilder()`)  end up with reasonable behaviour by default. (Though we might want to consider what `Normalize()` should do for these values; maybe it's okay for that to continue to throw `OverflowException`?).

Alternatively, we could instead add `Period.MinValue` and `Period.MaxValue` as sentinel representations of `-inf`/`+inf`, non-equal to all extant `Period`. In contrast, that _would_ give us a bijection (and in that case perhaps `NegativeInfinity` and `PositiveInfinity` would be better names). These values wouldn't actually have to have _any_ behaviour other than `Equals()` (and possibly `ToString()`?), since they'd only be used to represent out-of-range values, and could be non-constructible otherwise. However, I think this choice would add quite a lot of extra complexity, since we'd also have to consider what happens if you use these with other methods that take a `Period`, like `Period.Add` or `period.CreateComparer`. All in all, I think the other option is probably a better choice.

Separately, while it does seem a bit weird to be adding "min"/"max" values to a non-comparable type, I think it's fair to say that while we could imagine various reasonable total orderings over `Period`[^1], I think we can agree that most reasonable choices would have the same values for their lower- and upper-bounds, so I don't think that it's too confusing to do this.

[^1]: For example, another reasonable `Period` ordering would be to compare each component in order from biggest to smallest, which does have the advantage of being consistent with `Equals()`, but which wouldn't be at all consistent with how we normally think of periods in causal use.

I don't think we're proposing it, but I also don't think it'd be a good idea for `Period` to implement `IComparable<Period>`, given there's no true natural ordering for this concept. We already have `CreateComparer(LocalDateTime)` to return an `IComparer<Period>` using a base date/time; you could also imagine implementing a method (elsewhere) to return a Postgres-compatible `IComparer<Period>` that compared normalized periods using a 30-day month, and I think that would be a better choice if someone needed that.

**Comment by roji** [comment]
Yep, all the above makes sense to me. As you noted, we already map Instant.MaxValue to PG infinity although it also represents an actual value - the same is done with BCL DateTime; the logic here is that nobody actually wants to use MaxValue to specify a specific timestamp, only a value that's guaranteed to be larger than all others. So although a separate "infinity" value would be mathematically more correct (and this is BTW how PG does it), just having a plain MaxValue seems completely fine and the extra complexity of an infinite value doesn't seem worth it.

Re adding comparability to Period, I'd keep it a separate question, and only based on an actual user need - which I very much doubt we'll see.

**Comment by jskeet** [comment]
> and in that case perhaps NegativeInfinity and PositiveInfinity would be better names

I think that would be better than MinValue and MaxValue, if we're taking the sentinel approach. But it *definitely* complicates things - we have this for `Instant` (BeforeMinValue / AfterMaxValue) and we need to validate it on every operation. It's going to be significantly more work.

**Comment by azan-n** [comment]
> It's going to be significantly more work.

I don't mind helping out with it.

[Double.PositiveInfinity](https://learn.microsoft.com/en-us/dotnet/api/system.double.positiveinfinity?view=netcore-2.2) and [Double.NegativeInfinity](https://learn.microsoft.com/en-us/dotnet/api/system.double.negativeinfinity?view=netcore-2.2) sound great for this since they also prevent exceptions on overflowing operations. I'm curious to know if this is something that was explored in the past.

**Comment by azan-n** [comment]
@jskeet 

I see how `BeforeMinValue` and `AfterMaxValue` are working. 


I'm just thinking out loud but do you think we could add a private control value like an enum and use `Period.Zero` in conjunction with the enum to determine if the value is PostiveInfinity, NegativeInfinity, or neither?

```cs
// pardon the naming
enum Infinity {
  Positive,
  Negative,
  Neither  
}
```

```cs
public bool IsInfinity => Period.En == Positive || Period.En == Negative
```
