### ISSUE TITLE
Zoned date time to instant picking up Utc time component?

### ISSUE THREAD

**Issue by mwpowellhtx** [nodatime/nodatime#1819]
Bit confused, not sure where the additional time component is coming from here.

```csharp
// 1. when.Date, given DateTime.Now, wanting midnight instant: {2024-10-04 12:00:00 AM}
var ldt = LocalDateTime.FromDateTime(when.Date);

// 2. Assuming US/Eastern, want to gauge scenarios with server locality i.e. central: {US/Central}
var zone = DateTimeZoneProviders.Tzdb["US/Central"];

// 3. Obtain the ZonedDateTime, still in agreement 12:00:00 midnight: {2024-10-04T00:00:00 US/Central (-05)}
var zdt = ldt.InZoneStrictly(zone);

// 4. Showing: {2024-10-04T05:00:00Z}
var instant = zdt.ToInstant();
```

Actually now that I think about it... this must be the `Utc` equivalent, such that `Instant` may be ubiquitously compared. Which is our aim in this particular case.

**Comment by malcolmr** [comment]
Yes, 05:00 UTC (the `Z` in the `Instant` representation indicates UTC) is midnight in US/Central, at least for the date you were testing with.

You might want to take a look at our user guide, in particular [the concepts page](https://nodatime.org/userguide/concepts).

Closing this as not-an-issue (and note also that Stack Overflow is probably a better place to ask how-to questions about Noda Time, rather than this issue tracker).
