### ISSUE TITLE
Compile flag without BCL support (for SQLCLR)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#217]
```
Since SQL Server doesn't have any built-in support for time zone conversions 
(while Oracle and MySql have tzdb support built in), I thought I would try to 
use NodaTime from a SQLCLR user defined function.  This came up while I was 
looking into this question http://stackoverflow.com/q/16231482/634824

Apparently, it's really difficult to use the BCL TimeZoneInfo class from SQLCLR 
because it's marked with a HostProtection attribute with MayLeakOnAbort=true.  
(yikes)

So of course, I thought NodaTime would be a great alternative.  Well, at first, 
SQL wouldn't even load the NodaTime assembly into its catalog.  There's a few 
restrictions that static fields must be marked readonly.  We had a few that 
weren't.  Also, it didn't like caching the TimeZoneInfo.Local value in a static 
field, so I had to bypass that.  After working through the exceptions it 
complained about during loading, I was ultimately able to get the assembly to 
load and show up in the database's assembly catalog.

Then I wrote a simple SQL CLR function:

[SqlFunction]
public static SqlDateTime UtcToZone(SqlDateTime dateTime, SqlString zoneId)
{
  var zone = DateTimeZoneProviders.Tzdb[zoneId.Value];
  var dtUtc = DateTime.SpecifyKind(dateTime.Value, DateTimeKind.Utc);
  var instant = Instant.FromDateTimeUtc(dtUtc);
  var dtConverted = instant.InZone(zone).ToDateTimeUnspecified();
  return new SqlDateTime(dtConverted);
}

Of course, it needs some argument checking, but it should work as a simple 
test.  This loaded into SQL just fine.  Then I tried to run it, as such:

select dbo.UtcToZone(GETUTCDATE(), 'America/Phoenix')

And I fail again.  It seems just loading the NodaTime assembly initializes the 
Bcl DateTimeZone provider, and calls into TimeZoneInfo, which gives the same 
problems as before:

Msg 6522, Level 16, State 2, Line 7
A .NET Framework error occurred during execution of user-defined routine or 
aggregate "UtcToZone": 
System.TypeInitializationException: The type initializer for 
'NodaTime.DateTimeZoneProviders' threw an exception. ---> 
System.Security.HostProtectionException: Attempted to perform an operation that 
was forbidden by the CLR host.

The protected resources (only available with full trust) were: All
The demanded resources were: MayLeakOnAbort

System.Security.HostProtectionException: 
   at NodaTime.TimeZones.BclDateTimeZoneSource.GetIds()
   at NodaTime.TimeZones.DateTimeZoneCache..ctor(IDateTimeZoneSource source)
   at NodaTime.DateTimeZoneProviders..cctor()
System.TypeInitializationException: 
   at NodaTime.DateTimeZoneProviders.get_Tzdb()
   at NodaSQL.UserDefinedFunctions.UtcToZone(SqlDateTime dateTime, SqlString zoneId)
.


So, it looks like getting full NodaTime implementation is going to have the 
same problems because it references TimeZoneInfo.  Is there any way we could 
have some conditional compilation to compile NodaTime with only TZDB support?

Do you think even without this that we'd run into other SQL CLR restrictions?

```

Original issue reported on code.google.com by `mj1856` on 26 Apr 2013 at 10:48

**Comment by malcolmr** [comment]
Given that 1.4 is intended to be a bridge release, bumping this to 2.0-consider.

**Comment by tom3m** [comment]
Guys could you please give an update. Is SQLCLR support available at the moment anf if it is - what release it was included. Thank you.

**Comment by jskeet** [comment]
No, there's no released version that includes it - and I suspect it's *unlikely* to get into 2.0 unless someone else puts some effort into it. (I don't have bandwidth or motivation.)

**Comment by tom3m** [comment]
Ok, thanks for honest reply :) I suggest to close the issue with corresponding status

**Comment by mj1856** [comment]
Given that [SQL 2016 will have `AT TIME ZONE`](http://blogs.technet.com/b/dataplatforminsider/archive/2015/11/30/sql-server-2016-community-technology-preview-3-1-is-available.aspx), and there's good enough support in [my interim project](https://github.com/mj1856/SqlServerTimeZoneSupport), I don't have much motivation for porting NodaTime to SQLCLR now.  I'm ok with removing it from the road map.

**Comment by srutzky** [comment]
Hi there. Just to put this out there, I have been interested for a while now in helping out on this particular project. I was introduced to it by Matt earlier this year and thought that I would have had time by now, but it has been a crazy year (and then some). But, I am still interested in it. I still do seem some value in porting this to SQLCLR, even with the new `AT TIME ZONE` feature that Matt pointed out, given that people will be using SQL Server 2005 - 2014 for years to come (some poor souls are still on SQL Server 2000).  
That said, I am also aware that this ticket has been open for a while and I am unable to commit to any specific timeline at the moment. My desire is to do this within the next 6 months. But if the group feels that it is best to close this issue then that is fine as well. It will stay on my to-do list regardless, though :-).  
For some background on me: I have been working with SQLCLR since early 2006. I created a library of SQLCLR functions / stored procedures / aggregates / types called [SQL#](http://SQLsharp.com) that comes in both Free and Full (i.e. paid-for) versions. I also am writing a series of articles on SQLCLR for SQL Server Central: [Stairway to SQLCLR](http://www.sqlservercentral.com/stairway/105855/). While I do some work in C#, I am primarily focused on the database side of things, specifically SQL Server programming / data modeling / etc. My initial interest was in adding better TimeZone support to SQL Server and offering that in just the Full version of SQL#. But upon meeting Matt and finding out about this project, I figured I would just contribute to here and then incorporate a build of that into both the Free and Full versions of SQL# so that someone could have all of the functionality in a single package and not need to mess with two downloads. But if someone only wanted the NodeTime stuff and not SQL#, then they could get that from here.  
Does that all sound ok? Is this helpful at all? Should this issue remain open, or should it be closed and I just work on it if / when I can, and when I am done I just let all y'all know about it in a pull request? Or is there a better way of approaching / managing this?

**Comment by jskeet** [comment]
I removed it from the roadmap in commit f6ce3b32a72da4feedb574ccdd2b4bdd12b1c142, but it could still happen later.

I'm still open for it to happen if it can be done without making the rest of the codebase harder to read - given how much the code has changed since Matt last looked, it may be harder or possibly easier than it was before. I think it would be best to close this for now, and @srutzky can open a new issue or just a pull request if and when there's movement on it. My experience of "I'm hoping to be able to do it in about 6 months" is usually that it's more like 2 years, but maybe that's just me :)

**Comment by srutzky** [comment]
> My experience of "I'm hoping to be able to do it in about 6 months" is usually that it's more like 2 years, but maybe that's just me :)

No, not just you ;-). I was trying to be as open / honest as possible and careful to not overstate / over-promise (since anything can happen, hence why I didn't get to it 6 months ago) so that you could decide what was best for the project. And I think what you proposed is entirely reasonable. I will plan on getting to this when I am able to, and when I have something to show I will inquire as to the best approach with regards to new issue or just a pull request.
