### ISSUE TITLE
Reconsider the SPI for time zone mapping

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#282]
```
IDateTimeZoneSource.MapTimeZoneId() accepts a TimeZoneInfo, but we only ever 
call it with one value, the local time zone.  It seems like this is 
unnecessarily general, and we should probably reconsider for 2.0
```

Original issue reported on code.google.com by `malcolm.rowe` on 10 May 2014 at 10:13

**Comment by malcolmr** [comment]
In summary, I'd suggest replacing `IDateTimeZoneSource.MapTimeZoneId(TimeZoneInfo)` with `IDateTimeZoneSource.GetSystemDefaultId()` that returns the string ID.

In particular, note that the current arrangement requires sources to operate over an arbitrary BCL TimeZoneInfo, which may not be possible in some cases (PCL/netstandard).

(Note that we'd want to return the ID in case the system default timezone were to be "UTC", because then we'd want to return a fixed-offset timezone.)
