### ISSUE TITLE
Consider MonthDay and YearMonth

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#317]
```
java.time has types MonthDay and YearMonth.  Consider if we want these for Noda 
Time vNext.
```

Original issue reported on code.google.com by `mj1856` on 4 Aug 2014 at 5:44

**Comment by jskeet** [comment]
I've been approached about these types again, and I think it would be worth looking at them more closely. Will create a new branch to see what they could look like, in terms of operations.

**Comment by idg10** [comment]
I'd question whether MonthDay is the right name. It feels inconsistent with other names in NodaTime. (E.g., this feels akin to renaming LocalTime HoursMinutesSecondsMilliseconds.) It's just a description of what's inside, whereas most type names give a clue as to what they're for. So I'm wondering if RecurringDate, or AnnualDate, or even Anniversary might be more informative names.

**Comment by jskeet** [comment]
Starting to play with this a little... MonthDay feels useful (and that probably *is* what I'd name it - Anniversary feels like what someone might use it for, rather than what it represents; it's also consistent with Joda Time and Java 8).

YearMonth feels harder to pin down in terms of a use case. There's the argument that it's appropriate for (say) a credit card expiry date, but it feels like in that case it would be cleaner to represent it as a LocalDate anyway, to avoid the confusion about whether it expires at the end of the month or the start. (There's still the question about whether it expires at the end of the day or the start, admittedly.) It's easy enough to write the code - just harder to really justify its presence.

**Comment by MenoData** [comment]
There has been an interesting debate about this stuff among Java folks (Oracle and Threeten-team).

https://github.com/ThreeTen/threeten/issues/209

Naming `MonthDay` as `Anniversary` seems to be a good idea IMHO. About the other types like `YearMonth`, `YearQuarter` etc., I would mainly model such classes as date range intervals and source for iterating over full calendar dates (my plan for my own Java library Time4J in the future).

**Comment by jskeet** [comment]
@MenoData Thanks for that.

Anniversary feels like an odd name for a type used to store (say) the start of the UK tax year (April 6th). That's not an anniversary in that it's not remembering a particular event in *one* year, but several years later. MonthDay could certainly be used *for* anniversaries, but it's not uniquely for that. I think "MonthDay" gives a clearer indication of what it *is*, and then it can be used for whatever people want. But I'm still happy to be persuaded.

AnnualDate feels more reasonable to me. RecurringDate suggests that it may be part of a larger recurrence-handling API - which may be something we want to do at some point, of course...

**Comment by idg10** [comment]
I agree with you on Anniversary, despite having suggested it in the first place. I was just scratching around for names because MonthDay seems out of character with the rest of the API. Returning to this a month or so after making my suggestions, I think I prefer AnnualDate. (Or at least, I dislike it least out of the available options, including MonthDay.)

**Comment by MenoData** [comment]
@jskeet  AnnualDate also sounds fine for me. Since your English is definitely better than mine I will rather follow your advise in this naming question.

**Comment by jskeet** [comment]
On a flight, I tried implementing a load of this. I got quite a long way... but there are some *really* nasty corner cases with the Hebrew calendar system. Basically a month number on its own doesn't signify much in the civil month numbering system, due to the way leap years offset everything. So I came up with the idea of a "logical month number" which would always assume a leap year for calendar systems with a leap month... but that *still* doesn't cope with "Adar 30th" - because normally Adar would be mapped to Adar II in a leap year, but Adar II doesn't have 30 days, so we'd want to map "Adar 30th" to "Adar I, day 30". It's all really messy.

How much of a cop-out would it be to not support non-ISO calendars for AnnualDate/MonthDay/whatever we call it?

**Comment by idg10** [comment]
Speaking as someone who has been agitating for this feature, non-ISO calendar support wouldn't be a problem for my particular scenarios. I don't think I understand enough to grasp the exact problem here - is it that this whole concept doesn't actually make sense for some calendars? Or is it that it does but it's weird?

**Comment by jskeet** [comment]
For most calendars, I think it works reasonably - it's really the Hebrew calendar which is odd due to splitting Adar into Adar I and Adar II (two separate months) in leap years. So imagine the issue of "what happens to February 29th in a non-leap year?" and then apply it to a whole month being MIA.

Of course, we handle this already in period computations - but just *expressing* "Adar 20th" vs "Adar I 20th" vs "Adar II 20th" is blowing my mind a bit. I think it would make sense for it to be ISO-only to start with, and then expand later if we get the feature request. I'd rather support the 95% case simply than put a lot of extra machinery in (its gets really quite convoluted) for little reason.

**Comment by malcolmr** [comment]
Making this ISO-only sounds completely reasonable to me.

And you're right, I don't know how we could really make this make sense for the Hebrew calendar.

**Comment by mj1856** [comment]
FWIW, Java 8's implementation of `YearMonth` and `MonthDay` are both ISO only.

If we wanted to make it work with other calendars, I think it would have to be a hierarchy, as in.

```csharp
interface IYearMonth
struct YearMonth : IYearMonth
struct YearMonthLeap : IYearMonth

interface IMonthDay
struct MonthDay : IMonthDay
struct MonthDayLeap : IMonthDay
```

Of course, that just pushes down the decision of how to interpret the month value down to the caller.

**Comment by jskeet** [comment]
Closing this for now as we have the functionality - still up for grabs is naming and possibly text parsing/formatting.

(Given that XSD has MonthDay, I'm more encouraged to go back to that...)
