### ISSUE TITLE
incompatible offsetdatetime with objective c datetime timezone offset

### ISSUE THREAD

**Issue by ahmettaha** [nodatime/nodatime#357]
Hello,

In objective c the datetime's are serialized as below.

2015-03-20T19:40:30+0200

However, nodatime doesnt parse this. It required as below

2015-03-20T19:40:30+02:00

Objective c follows the following convention:

http://unicode.org/reports/tr35/tr35-6.html#Date_Format_Patterns

How can I make nodatime parsers follow the same convention and accept datetimes without column.

thank you.

**Comment by malcolmr** [comment]
It's not entirely clear to me how you're trying to parse those strings (or exactly which conventions you're pointing to: TR35 talks about patterns in general, but doesn't seem to recommend one), but there's nothing special about the default patterns other than that they're predefined (as e.g. `OffsetDateTimePattern.GeneralIsoPattern`).

In other words, instead of doing something like this:

```c#
string input = "2015-03-20T19:40:30+02:00";
OffsetDateTimePattern pattern = OffsetDateTimePattern.GeneralIsoPattern;
OffsetDateTime parsed = pattern.Parse(input).Value;
Console.WriteLine(parsed);
```

where `GeneralIsoPattern` [is equivalent to](http://nodatime.org/api/html/P_NodaTime_Text_OffsetDateTimePattern_GeneralIsoPattern.htm) the pattern `yyyy'-'MM'-'dd'T'HH':'mm':'sso<G>`, you can instead use a custom pattern that replaces the offset part (`G`, which uses colons) with something else:

```c#
string input = "2015-03-20T19:40:30+0200";
OffsetDateTimePattern pattern = OffsetDateTimePattern.CreateWithInvariantCulture(
    "yyyy'-'MM'-'dd'T'HH':'mm':'sso<+HHmm>");
parsed = pattern.Parse(input).Value;
Console.WriteLine(parsed);
```

See also the [user guide on OffsetDateTime patterns](http://nodatime.org/userguide/offsetdatetime-patterns.html) (which for `OffsetDateTime` delegates to the patterns for `LocalDateTime` and `Offset`.

**Comment by ahmettaha** [comment]
Hello,

Sorry, you are right. I have forgotten how I'm parsing these. I'm using json.net binder with web.api. so is there a way to change the expected pattern for web.api bindings?

when using this

  jsonFormatter.SerializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

**Comment by jskeet** [comment]
Hmm. You could try to basically overwrite the existing serializer - have a look at how ConfigureForNodaTime works, and do something similar for `OffsetDateTimePattern` but with the pattern given by Malcolm. `NodaPatternConverter` is public, so that part should be fairly easy - you'd need to duplicate the code for ReplaceExistingConverter though (https://github.com/nodatime/nodatime/blob/master/src/NodaTime.Serialization.JsonNet/Extensions.cs#L115).

Possibly it would be worth exposing that as an extension method...

**Comment by ahmettaha** [comment]
I'm not sure, I understood what you are asking me to do? Can you please write it again.

Also, I couldnt build the master branch. it's giving me error for the following lines

 public long Nanoseconds => unchecked(seconds * NanosecondsPerSecond);

it doesnt like the "=>" notation

**Comment by ahmettaha** [comment]
Nevermind. I got it :)

thank you.
