### ISSUE TITLE
Fixed offset time zone names

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#363]
As noted in issue #361, fixed offset time zones end up using the zone ID as the name within zone intervals, effectively ignoring the name within the source data.

Unfortunately this is baked into the serialization format, which makes things tricky...

**Comment by malcolmr** [comment]
This is in the serialization format because the constructor for `FixedDateTimeZone` accepts only an ID and offset, so we'd need to fix that, too.

I don't see that it should be that hard to do this in a backward-compatible fashion, though: we can extend the existing fixed-zone data for the time zone field with additional data, can't we? (The only hard bit is providing a "read string if present" method on `DateTimeZoneReader`, I think.)

**Comment by jskeet** [comment]
We may be able to. I don't know whether we currently check (in existing public out-there builds) that we've exhausted all of the data in a stream when we're done. If we don't, then putting it at the end of the serialization format is indeed the way forward.

**Comment by jskeet** [comment]
Fixed in commits:
37e5f46a71dab4a066ac187e6ede8c1ea341a900
5c4e1e980d02a26aa87ebe611fc0466c76db2f1b
f04d357cd0be11ce0a57b8bfd0b0de35cda6c44f
