### ISSUE TITLE
Consider string overloads for InZone, etc.

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#376]
1.x:
```csharp
DateTimeZone tz = DateTimeZoneProviders.Tzdb["America/New_York"];
ZonedDateTime now = SystemClock.Instance.Now.InZone(tz);
LocalDate today = now.Date;
```

2.0 (current)
```csharp
DateTimeZone tz = DateTimeZoneProviders.Tzdb["America/New_York"];
LocalDate today = SystemClock.Instance.InZone(tz).GetCurrentDate();
```

IMHO, it would be nice to make this even simpler by adding string overloads to all `InZone*` methods.  

Proposed:
```csharp
LocalDate today = SystemClock.Instance.InZone("America/New_York").GetCurrentDate();
```

I think it would be ok to default to TZDB zones for this overload.  Alternatively, we could search TZDB zones first, then BCL zones second.

Thoughts?

**Comment by jskeet** [comment]
I'd really like to avoid defaulting time zone providers anywhere, to be honest. Currently we do that for serialization but that's *all*. It feels like a slippery slope from allowing a string in one places to defaulting all over the place.

What we could do is provide sample code which would let users add their own extension method to `IClock` easily - then *they* can pick the default appropriately, if they want to. That feels cleaner to me - more deliberate. (Just like I've always said that if people really want to have static methods to use the system clock rather than dependency injection, it's an easy class to write - it's just one I wouldn't want to be in Noda Time itself.)

**Comment by mj1856** [comment]
Sure, I suppose it's no more complicated than this:

```csharp
    public static ZonedClock InZone(this IClock clock, string tzdbZoneId)
    {
        return clock.InZone(DateTimeZoneProviders.Tzdb[tzdbZoneId]);
    }
```

I guess that's just as easy to add to end-user code and samples as it would be to add to the core library.
