### ISSUE TITLE
Add rounding and sampling functions

### ISSUE THREAD

**Issue by filmor** [nodatime/nodatime#379]
A common need (at least for me) is to take a zoned datetime and round it to the next or previous quarter or half or full hour. This can also be used to implement sampling at the requested frequency by always taking an aligned value, adding a tick and realign to the next period.

Is this something that you'd like to have in the library or would you prefer this to be external? Any preferences on the API design?

I'd prepare a PR for this if this may be included.

**Comment by jskeet** [comment]
In NodaTime 2.0 this would be done via a time adjuster:
https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeAdjusters.cs

It would make sense to have a "round to" adjuster - although there are lots of variations, so it needs a bit of care to get the API right so that it doesn't balloon. (We've already got "TruncateToHour/Minute/Second" but it sounds like you need more than that.)

Once you've got a `Func<LocalTime, LocalTime>` that can be applied to a `LocalTime` ,`LocalDateTime`, `OffsetDateTime` - but not currently a `ZonedDateTime`, for the same reasons normal arithmetic can't be performed on `ZonedDateTime` values. I can see how it would be useful, but there are lots of corner cases to consider...

**Comment by filmor** [comment]
This is the solution that we currently use:

        internal static Instant GetReference(this Instant me, Duration d)
        {
            return (me - d).InUtc().Date.AtMidnight().InUtc().ToInstant();
        }

        public static Instant Align(this Instant me, Duration d, Instant? reference = null)
        {
            // Choose midnight on a day one duration before me as a reference
            var myref = reference ?? me.GetReference(d);
            long delta = (me - myref).Ticks / d.Ticks;
            return myref + delta * d;
        }

        public static Instant AlignNext(this Instant me, Duration d, Instant? reference = null)
        {
            return (me + d).Align(d, reference);
        }

In case of a `ZonedDateTime` a different `GetReference` method gets midnight in that timezone.

**Comment by jskeet** [comment]
Closing as I suspect this is a niche requirement, and a suitable adjuster can be written fairly easily (which will then integrate with all the existing methods).

**Comment by filmor** [comment]
Would you be open to include such an adjuster in the default package?

**Comment by jskeet** [comment]
Not quite as written - that's effectively rooted based on the Unix epoch, which may well not be appropriate. If we can design an API that's more general, I'd be happy to include that.

**Comment by filmor** [comment]
For the example code it's not rooted on the Unix epoch, it's rooted on whatever reference you pass or on midnight in UTC. Depending on how the adjuster interface looks, it should probably just take midnight in the respective timezone instead.

**Comment by jskeet** [comment]
Ah - I misread. (Sorry, was distracted.) We'd need to adjust it to nanoseconds now... but I'm not sure whether we use adjusters for instants. Is that what you actually end up needing it for, or a `ZonedDateTime`?

Basically I'm not against the general idea, but I think there's a bit of work needed before it's suitable.
