### ISSUE TITLE
finding offset with respect to daylight savings time

### ISSUE THREAD

**Issue by ahmettaha** [nodatime/nodatime#387]
Hello,

i use the following code to find offset between a timezone and utc.
```
DateTimeZone TimeZone =  DateTimeZoneProviders.Tzdb["America/Chicago"];
int offset = TimeZone.GetUtcOffset(SystemClock.Instance.Now).ToTimeSpan().Hours
```
When I do this, the offset value is -5. However, because of dst google tells me that chicago is right now -6

![screen shot 2015-10-02 at 10 47 14](https://cloud.githubusercontent.com/assets/2559157/10241589/fa142bf6-68f2-11e5-9db0-50ccdd595c0f.jpg)

How do I find the offset with respect to dst?

thanks.

**Comment by jskeet** [comment]
You're doing the right thing (well, sort of - I'd keep it as an `Offset` but that's a different matter). Noda Time is returning the right time, too - it *is* UTC-5, because CST is UTC-6 and CDT is UTC-5. When I perform a Google search for "what is the time in Chicago" it gives me the right time...

It's not clear what you did to see the result you've shown in the screenshot, but I suspect it's trying to say that the Central Time Zone is UTC-6 in standard time. If you can give me details about how you got to that, I can file an issue to make that clearer... but this definitely isn't a problem with Noda Time :)

**Comment by ahmettaha** [comment]
I googled 

America/Chicago timezone

and it gave me that result.



.

**Comment by jskeet** [comment]
Thanks. Will file an issue to see if Google can make that clearer. (I'm not promising anything, of course.)
