### ISSUE TITLE
Instant.ToDateTimeOffset Method Throws ArgumentException When Offset Contains Seconds

### ISSUE THREAD

**Issue by LindosPechos** [nodatime/nodatime#395]
Instant.ToDateTimeOffset method will throw a SystemArgumentException "Offset must be specified in whole minutes" from the DateTimeOffset class when the Instant contains an offset with seconds (ie. -04:19:18). See the [MSDN TimeSpan ArgumentException](https://msdn.microsoft.com/en-us/library/bb351980%28v=vs.110%29.aspx) for more details.

This issue can occur very frequently when a system deals with dates prior to the late 1890's. It was around this time in history that various locales standardized their time zone. For the period before this time the offset looks to be more of a calculated value which typically contains seconds.

**Examples of these Offsets**

| Time Zone | Offset | Until |
| --- | --- | --- |
| Atlantic/Bermuda | -04:19:18 | 1930 Jan 1 02:00 |
| America/Mazatlan | -07:05:40 | 1921 Dec 31 23:54:20 |
| Pacific/Honolulu | -10:31:26 | 1896 Jan 13 12:00 |

@jskeet post here contains hundreds of examples of the points in history when these offsets containing seconds occur:
https://github.com/nodatime/nodatime/blob/master/data/tzdb/2015a/northamerica

**Example To Reproduce The Exception**

``` C#
DateTime dt = DateTime.Parse("1896-01-12 00:00:00.000");
DateTimeZone tz = DateTimeZoneProviders.Tzdb["Pacific/Honolulu"];
LocalDateTime localDt = LocalDateTime.FromDateTime(dt);
ZoneLocalMappingResolver customResolver = Resolvers.CreateMappingResolver(Resolvers.ReturnLater, Resolvers.ReturnStartOfIntervalAfter);
ZonedDateTime zdt = localDt.InZone(tz, customResolver);  // dzt.Offset results in -10:31:26
DateTimeOffset dto = zdt.ToDateTimeOffset();  // <- Exception is thrown here.
```

**Work Around**
Create a new DateTimeOffset object using a TimeSpan object created from the Hours and Minutes of the Offset from the converted ZonedDateTime object and set the seconds value to zero.

**Work Around Example**

``` C#
...
ZonedDateTime zdt = localDt.InZone(tz, customResolver);  // dzt.Offset results in -10:31:26
TimeSpan tsTemp = zdt.Offset.ToTimeSpan();
TimeSpan ts = new TimeSpan(tsTemp.Hours, tsTemp.Minutes, 0); // Set seconds to zero.
DateTimeOffset dto = new DateTimeOffset(zdt.Year, zdt.Month, zdt.Day, zdt.Hour, zdt.Minute, zdt.Second, zdt.Millisecond, ts);
```

**Comment by jskeet** [comment]
Thanks very much for raising the issue - I'm not sure I like the workaround though, as it's silently losing information. I think an exception is reasonable, although it should probably be a better one.

How about an extension method of `ToDateTimeLossy()` or something similar?

**Comment by LindosPechos** [comment]
Which information are you referring to that is being silently lost, the Offset seconds? Being that the Microsoft DateTimeOffset object does not support seconds as part of the Offset I feel that there really isn't a loss of information here.

In regards to the addition of an extension method, that may be the way to go. What would you propose the method would perform and return?

**Comment by jskeet** [comment]
It's still losing information in the same way that casting 1.5 to 1 is losing information - it's a non-reversible transformation.

It definitely *is* losing information, even though that's unavoidable here. (If it were avoidable, I'd just fix the bug :)

I'd suggest that the extension method should behave as you've suggested, returning a DateTimeOffset which just truncates the seconds. I'm just proposing that the simple ToDateTimeOffset method should throw instead of silently truncating :)

**Comment by LindosPechos** [comment]
Yes, I agree that modifying the existing ```ToDateTimeOffset()``` method to truncate the seconds would result in unexpected loss of information. You're suggestion of adding an additional extension method to perform the truncation does makes sense. Adding ```ToDateTimeOffsetLossy()``` sounds like a good alternative. The developer then of course would be responsible for calling the correct DateTimeOffset converter depending on the date value.

Thanks for your suggestion and for this great library you have put together.

**Comment by mj1856** [comment]
@jskeet - what would be the effect of increasing the precision for `Offset` (and `OffsetDateTime`, et. al) for 2.x?

**Comment by jskeet** [comment]
The problem isn't the precision of `Offset` - the problem is the precision of `DateTimeOffset`. We've actually *reduced* the precision of `Offset` from milliseconds to seconds in 2.x, on the grounds that we don't need sub-second precision, but we can't change what `DateTimeOffset` will accept as a valid offset.

**Comment by jskeet** [comment]
(Although to speak to your question a little more, the effect of increasing the precision of `OffsetDateTime` and the like from ticks to nanoseconds in 2.x is that *all* conversions to `DateTime` and `DateTimeOffset` are potentially lossy in 2.0 - but only at the sub-tick level, which is a little less surprising than losing whole seconds, IMO.)

**Comment by mj1856** [comment]
Oh, I misunderstood.  That makes sense. Thanks.

IMHO, I'd rather `Instant.ToDateTimeOffset` just lose precision than throwing an exception.  I don't see the need for `ToDateTimeOffsetLossy`

**Comment by jskeet** [comment]
I hadn't even spotted the change in author :) The fact that `ToDateTimeOffset` is going to become potentially lossy in 2.0 does sway me slightly. As I say, losing whole seconds feels non-ideal though. What about offsets outside the range that DateTimeOffset supports, e.g. +/- 15 hours? Should that still throw? (I think it should.)

If the offset is going to lose precision, should the result be adjusted to reflect the same local time, or the same UTC time?

**Comment by mj1856** [comment]
Actually, DTO offsets are +/- 14 hours - though that seems like that number was chosen arbitrarily.  (Let's hope Kiritimati never decides to use DST)

Yes, I think it should throw if outside that range.

The other question is quite interesting.

- On one hand, I could argue that both `Instant` and `DateTimeOffset` are intended to represent a specific moment in time, so the precision loss on the offset could be balanced by the date and time part such that the two still represent the same instant.

- Then again, the usage of offsets with sub-minute precision is usually limited with early data LMT values, as mentioned in the original post.  In that context, I think it would be more important to retain the local time value - especially if keeping the precision meant that the local *date* might change if the value was near midnight.

Since either approach seems valid, and our philosophy is to not make assumptions, I would prefer to let the developer specify.  Perhaps we should add an overload to take an enum, either `LossyBehavior.SameInstant` or `LossyBehavior.SameLocalTime`.

**Comment by jskeet** [comment]
And if we allow LossyBehavior.Throw as well, we can make those who never want to lose any information happy too :)

**Comment by mj1856** [comment]
:+1:

**Comment by malcolmr** [comment]
I note that despite the issue title, we're actually talking about two different problems:

1. All of `Instant.ToDateTimeOffset()`, `OffsetDateTime.ToDateTimeOffset()`, and `ZonedDateTime.ToDateTimeOffset()` are lossy in 2.0 in respect of rounding towards the tick closest to the Unix epoch. (This is already as-implemented, but we should document it.)

2. `OffsetDateTime.ToDateTimeOffset()` and `ZonedDateTime.ToDateTimeOffset()` (but not `Instant.ToDateTimeOffset()`!) currently fail in Noda Time 1.x and 2.0 if using an offset that is outside the domain accepted by `DateTimeOffset`, whether due to being outside of the [-14 hour, +14 hour] range, or by having sub-minute offsets (see #304 for background on the first: there _are_ some historical cases that are outside that range).

For the second point above, I think that __by far__ the common case is that you _aren't_ dealing with a (historical) zone that has sub-minute offsets, or offsets outside [-14, +14], and so the current behaviour of `ToDateTimeOffset()` throwing is completely reasonable, imo (though it should throw a more sensible exception than it does).

I do think it would also be reasonable to introduce an `Instant.ToDateTimeOffset(enum)` overload for the other cases (though I perhaps would suggest we name that enum something other than `LossyBehavio(u)r`).

**Comment by jskeet** [comment]
The third situation to consider is that the OffsetDateTime represents a value which is outside the range supported by DateTimeOffset, e.g. in 500BC. Beyond that, I agree with Malcolm.

The part about rounding towards the Unix epoch is interesting, btw - in some places we round towards the start of time instead. I wonder whether it's worth putting some effort into trying to round uniformly. (Rounding towards the start of time in all cases has the benefit that it's epoch-neutral.)

**Comment by jskeet** [comment]
Note to self: I believe `Instant.ToDateTimeOffset()` already rounds towards the start of time and is documented to do so. `OffsetDateTime.ToDateTimeOffset()` doesn't have documented behaviour.

Will add tests and ensure there's correct documentation. In general, I want to take the approach of "round towards zero for neutral types (e.g. Duration), round towards start of time otherwise". I want the epoch to be an implementation detail as far as possible.
