### ISSUE TITLE
Switch decimal use in Duration's API to BigInteger

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#447]
We added `Duration.FromNanoseconds(decimal)` and `Duration.ToDecimalNanoseconds()` for 2.0.

However, since we're now (definitely?) going to depend upon .NET 4.0, we should consider replacing those with `Duration.FromNanoseconds(BigInteger)` and `Duration.ToBigIntegerNanoseconds()` instead, at least partly because `BigInteger` documents that we won't have a fractional part.

**Comment by fubar-coder** [comment]
I'm not sure if this is a good change, because it prevents compilation for .NET 2.0/3.5, NETStandard 1.0, and .NET Portable (Profiles 328 and 259)

**Comment by jskeet** [comment]
Noda Time 2.0 already doesn't support .NET 2.0 or 3.5. netstandard 1.0 doesn't work due to other issues - we have to use netstandard 1.3, and that's fine with BigInteger. I don't have a firm plan in terms of supporting old-school PCLs rather than netstandard... I can investigate that further though.

**Comment by jskeet** [comment]
Looks like a dependency on `System.Runtime.Numerics` shouldn't block much:

https://www.nuget.org/packages/System.Runtime.Numerics/

**Comment by fubar-coder** [comment]
I'll create a pull request that includes the following changes:

- Support for netstandard1.1 (first version supporting BigInteger)
- Support for net40
- Simplified dependencies
