### ISSUE TITLE
Is there a fluent API for writing tests?

### ISSUE THREAD

**Issue by SurajGupta** [nodatime/nodatime#576]
Does anyone know of a package that provides a fluent API for writing unit tests that use NodaTime?  I'm thinking something like:

`var myLocalDate = 3.September(2016)`

**Comment by jskeet** [comment]
I'm planning on putting exactly that kind of extension method into NodaTime.Testing - I just haven't done so yet.

Will leave this issue open to remind me to do it :)

(Of course, that will be for 2.0... although I could easily backport it for 1.4, which is intended to be a "compatibility release" to help migration to 2.0)

**Comment by SurajGupta** [comment]
That's fantastic!  I think it would be useful to have this in the latest stable version, whether that's 1.4 if 2.0 is still a pre-release package, or 2.0 if the stable version is released before this new testing component is available.

**Comment by jskeet** [comment]
2.0 isn't stable yet, and 1.4 doesn't exist at all :( The plan is for 1.4 to reflect the members that have been renamed/changed in 2.0, so that users can migrate via that. I'm not expecting to create it until fairly soon before 2.0 is released.

Now we *could* do a NodaTime.Testing 1.4 that depends on NodaTime 1.3.2, and add extension methods in there... then consider making NodaTime 1.5 for what was going to be NodaTime 1.4. Will think about it - there's nothing stopping it technically, but I'm not sure that these extension methods are worth a whole extra release.

Perhaps if I just create the code for 2.0 soon, you could temporarily include that source code directly in your project?

**Comment by SurajGupta** [comment]
I wouldn't do anything special just for me; I think it should be sequenced in a way that makes most sense for the overall project.  I like the idea of doing a 1.4 release of NodaTime.Testing that depends on NodaTime 1.3.2.  Although it's an extra release, it's in the Testing project so it should have a far smaller impact than if the release was for NodaTime itself (nuget.org shows ~45K downloads for Testing versus ~450K for NodaTime).  Downside is that NodaTime and NodaTime.Testing now have a different "latest stable" version, so not sure how much that bothers you, but that would go away with 1.5 (assuming that NodaTime.Testing would get rev'ed because of dependency on NodaTime).  My basic request is that the enhancements to Testing be made available in a non-pre-release package.  I think how this is sequenced is highly dependent on how much work is left for the "bridge" release.
