### ISSUE TITLE
Find User Timezone  from Timeoffset

### ISSUE THREAD

**Issue by qadeemakhtar** [nodatime/nodatime#648]
how can i Get User TimeZone  using Time-offset  which i Got from  new Date().getTimezoneOffset() JavaScript Function

**Comment by jskeet** [comment]
You can't find a single time zone that way - there may be multiple time zones which match. In order to work out the time zone, you'd ideally find the offset at a *set* of times.

Note that there are already Javascript libraries which perform this sort of detection for you - it's probably best to do it client-side and then just pass the ID to the server.

**Comment by jskeet** [comment]
With no other feedback after 5 days, I'm closing this for now - I don't think there's anything to do from the Noda Time side of things.
