### ISSUE TITLE
Representing "Ayyam-i-Ha" in the Wondrous calendar

### ISSUE THREAD

**Issue by glittle** [nodatime/nodatime#689]
Hi Jon,

I've been struggling with how to represent the "the days in excess of the months" (called Ayyam-i-Ha) in NodaTime...

Here's a diagram of how these "excess days" fit in the calendar:

![ayyam-i-ha 2](https://cloud.githubusercontent.com/assets/85186/23832658/ce8e8c00-06fe-11e7-8ab4-85ec34c1f33d.png)

On the surface, it is quite simple. Each year has a set number of these extra days, usually 4 or 5. The number in any particular year is predetermined using astronomical calculations based on the exact timing of the vernal equinoxes and local sunset times in Tehran, etc.. For NodaTime, a simple table of the answers is pre-loaded and is trivial to use.

The difficulty I'm facing is how to represent these days in NodaTime in relation to the months:

- Treat Ayyam-i-Ha as month 0. This will cause problems if 0 is treated as unknown. This is a problem because the base classes convert to 0-based months and don't allow negative numbers.
- Treat Ayyam-i-Ha as month -1. This is a problem because the base classes convert to 0-based months and don't allow negative numbers.
- Treat Ayyam-i-Ha as month 19. This is confusing because the "real" 19th month would be displayed as "month 20" which is meaningless.
- Treat Ayyam-i-Ha as month 20. This will cause problems if months are assumed to be sequential.
- Treat Ayyam-i-Ha as extra days in month 18. This would require special handling to sometimes display days in "month 18" as being Ayyam-i-Ha and we have no direct control over the display of dates.

The approach that seems to work best is to treat the Ayyam-i-Ha as month 20. The code I've currently committed to my fork of the "badi" branch does this. It all works great until we run into code that assumes that months are sequential. The other difficulty is that adding/subtracting days is not given to the Calendar implementation to do (as adding/subtracting months is) but is done directly so cannot account for this special "month".

Is there an approach that might solve these problems?

**Comment by jskeet** [comment]
I would treat it as being month 18. All kinds of things become odd if month 20 comes before month 19.
Yes, the "real" month 19 then ends up as month 20... but I think that can be clearly documented, and becomes a display consideration rather than anything else. Fundamentally, I'm afraid a calendar system which has such an odd aspect is likely to end up causing issues whatever else happens - the Hebrew calendar having an extra month is bad enough, in terms of distorting the numbers of other months (or making the year number change at odd times).

Treating it as month 18 means we can leave the rest of Noda Time alone - I would really not want to start tinkering with the rest of the codebase to assume that months can be negative or come out of order.

If we don't do that, I think the second best approach would be to treat month 18 as being longer - again, you'd need to make any display code aware of that, but that seems pretty unavoidable. If you really have "no control over the display of dates" in your actual *usage* of the calendar, I think it's unlikely that anything Noda Time does is going to help you, I'm afraid.

**Comment by MenoData** [comment]
@glittle You have shown an interesting problem in modelling other calendars with "exotic" features.

I don't know if you are constrained to C#-world only, but maybe my Java-library Time4J is interesting so far as kind of template because it uses a field concept which is not automatically fixed/linked to continuous integer numbers. And I think this is the main difficulty here, namely being forced to use numbers for months where the Ayyam-i-ha-period does not really fit in. It would be possible in context of Time4J to use interfaces and/or month-objects or ayyam-i-ha-objects as field values to overcome such difficulties in correct counting or formatting. Just giving an idea how to come out of the modelling dilemma.

For comparison, actually I am working on the old lunisolar Japanese calendar. This calendar sometimes has leap months which use the **same!** number as the preceding month in an arbitrary position during the lunisolar year and can only be recognized as leap months by an extra char (in Japanese the kanji 閏 followed by the month number and a month literal). So this example also shows that simple integer month models like in Gregorian calendar (1-12) can fail. And there are surprisingly many calendars with days which do not even belong to any month (French Revolutionary calendar, Discordian calendar, ...).

**Comment by glittle** [comment]
Thanks, @MenoData. I've implemented the Wondrous calendar in a number of different tools. However, most of them were concerned only with displaying the date, usually converted from the computer's gregorian calendar. For those, I've usually stored Ayyam-i-ha as month 0. Then it has been up to the display code to handle that and adapt the display accordingly. In one system, the display routine converts that to 18.5 to make it display between months 18 and 19.

(You can see that in action at https://wondrous-badi.today/. If viewed on a computer in Chrome, run this in the console to temporarily (until the next minute tick) switch to a day in Ayyam-i-Ha:  `doPulse(new Date(2017,1,27,12,0,0))`. When showing a day in Ayyam-i-Ha, it doesn't claim to be in a month.)

How to handle and display these intercalary days that are not in a month is an ongoing challenge!

For NodaTime, I wonder whether the storage of the date can be an internal structure that is exposed only through the Calendar implementation. That would allow the underlying structure to remain exactly as it is now for all calendars. Any calendars with unusual structures can do what they want in that internal structure. So, I could use month 20 to represent the Ayyam-i-Ha; the lunisolar Japanese could store the leap month as 13, but display it as whatever it should be for that year; etc.  This would have to include date display, comparison and calculations so that the internal code in the Calendar would have to determine "before" and "after", implement "ToString", etc.

From what I can see, NodaTime is based on translating all dates to the epoch date. That should allow every calendar to do what needs to be done based on epoch dates. However, I was finding that some non-calendar code assumes that, for example, month 11 comes immediately before month 12. But if a calendar inserts a leap month between them, that is not true. When I tried to store the Ayyam-i-Ha as month 20, various calculations outside of the Calendar implementation were not cooperating!

When I feel up to it, I will try again to see whether I can find a way to implement this for the Wondrous calendar!

**Comment by jskeet** [comment]
Yes, Noda Time assumes that calendars work in a fairly obvious way - the only calendar we implement that *isn't* fairly straightforward is the Hebrew calendar where the leap month is awkward in terms of when the year changes (in one numbering but not another).

At some stage there's always going to be a balance between "complete flexibility to support every calendar system ever" and "a maintainable code base and easy-to-use API that supports 99.9% of developers as well as possible". Noda Time clearly leans on the latter as being more important.

**Comment by glittle** [comment]
@MenoData, more to your question about my ideal model... I'm not really sure. Beyond NodaTime, I'm mostly focused on Javascript (various browsers and Node.js) so can't easily rely on subclassing.

For NodaTime, I would be fine with storing the Ayyam-i-Ha as month 20 so that the internal structures can handle it. 

I keep thinking that it would all work fine if more of the "default" functionality was moved into the default Calendar implementation, so it can be overridable in other Calendars. Does that make sense, @jskeet?

**Comment by jskeet** [comment]
@glittle: Unfortunately that makes it really hard to depend on any particular behaviour from elsewhere in the code. Basically it comes back to the balance at the end of the previous comment. (This is the same reason we don't support leap seconds, or Gregorian/Julian cutovers, or relatively, or Martian time...)

**Comment by MenoData** [comment]
@glittle Thanks for your insights. Just one correction about old Japanese calendar: It is not correct to store the leap month as month 13 (or zero or other number outside of 1-12) and then to handle how to display it because this would loose the information when such a leap month really occurred during a lunisolar year.

And I prefer not to work with magic numbers in general. Magic numbers can confuse users very much and lead them into the totally wrong direction. For example: Month "20" in Badi calendar is not after 19th month as you know but between 18 and 19 (and is not even a real month). Better IMHO to write in a more self-documenting style and to have example demonstrations in API documentation, for example this pseudo-code: 

```
if (badiDate.isMonth()) {
 ... // do month stuff
} else {
 ... // do ayyam-i-ha-stuff
}
```

**Comment by glittle** [comment]
@jskeet Do you know if anything has changed in the codebase since this discussion that might impact this problem?

**Comment by jskeet** [comment]
Nope, it's pretty fundamental to Noda Time that months are contiguous and start from 1.

**Comment by glittle** [comment]
I am looking at this again and am going to treat the Ayyam-i-Ha days as extra days in month 18.  However, the public methods would treat Ayyam-i-Ha as month 0.

I've now run into a different issue, that should be solvable.

When a new `LocalDate` is created, the `Calendar` system can be supplied. This is great. However, the calendar system code is now allowed to help when the date is being made - all it can do is do precondition checks. The `calendar` is asked to check these numbers but the numbers are used as is in making an object using the Ordinal calendar. The code (at line 111 of LocalDate.cs) is:
````
            calendar.ValidateYearMonthDay(year, month, day);
            yearMonthDayCalendar = new YearMonthDayCalendar(year, month, day, calendar.Ordinal);
````

Before the numbers are given to the Ordinal calendar, I need to be able to adjust them. It would work if there was a new method, say, `ValidateAndAdjustYearMonthDay` that is used here instead.
````
            calendar.ValidateAndAdjustYearMonthDay(ref year, ref month, ref day);
            yearMonthDayCalendar = new YearMonthDayCalendar(year, month, day, calendar.Ordinal);
````

In the base calendar, the `ValidateAndAdjustYearMonthDay` method could simply call the `ValidateYearMonthDay` as is done now. But this would give each calendar system the opportunity to make adjustments as needed to fit into the Ordinal calendar.

So, the user could say `new LocalDate(123,0,2,CalendarSystem.Wondrous)` for the 2nd day in Ayyam-i-Ha, and the calendar would adjust that to be saved as extra days in month 18... year (123), month (18), day (21).

Can I proceed with this approach and add such a new method?

**Comment by jskeet** [comment]
No, a calendar can't alter the day/month/year values the user passes in. It can validate them, but it can't change them, and I don't want it to be able to change them. If the user passes in month 0, I'd expect that to either be preserved or rejected. To be honest, at the moment I'm not sure it can be properly represented anyway, as the values in YearMonthDayCalendar and YearMonthDay are offset by 1 internally. There's an assumption that all month and day values start at 1. (Years can be negative.)

You seem to be a bit confused about `calendar.Ordinal` - that's just an integer identifying the calendar. There's no "Ordinal calendar" in the way that there's a Julian calendar or a Hebrew calendar.

The more you talk about the changes needed to integrate the Wondrous calendar into Noda Time, the less it seems like a good idea, to be honest. I doubt that you'll end up with something that really satisfies you, and the additional complexity and potentially performance impact is unlikely to satisfy anyone who *doesn't* want to use this calendar. So much of Noda Time relies on assumptions that have proved reasonable for all the other calendars we've implemented, but which don't work for the Wondrous calendar - and which will be very hard to unpick and "unassume".

**Comment by glittle** [comment]
I think I've worked out a compromise that works well. No changes to the existing code are needed, so there is no impact on others. I added some extension methods to LocalDate but didn't want people to see them unless they wanted to use the Wondrous calendar, so put the helper class into a sub-namespace inside `Calendars`.

I've committed the changes to the "badi" branch for your review.

If you are okay with what's been done, I can work on documentation in the code and for the website.

**Comment by jskeet** [comment]
I'll have a look when I've got some time, but I doubt that it'll be before the end of the week.

**Comment by glittle** [comment]
Sounds good. There's no particular rush... I'd rather it be done right.

**Comment by jskeet** [comment]
I think now would be a good time to create a pull request for a more normal review to merge into master.

It would be helpful if you'd either put that in a single commit, or separate it into logical commits which will make sense in the change history (rather than a set which records the various back and forth which has happened over time).

If this were me, I would probably go to a single commit, and then see whether it makes sense to split it up:

- Checkout the master branch
- Pull upstream master
- Checkout your badi branch
- Rebase to master so you've got everything in there
- Reset to master so that you're basically at "no commits, but all the changes locally"
- Commit everything, either in one go or multiple commits
- Push your badi branch to your fork
- Create a pull request against master

If you're happy doing that, I'll delete the badi branch on the main nodatime/nodatime repo, as that will no longer be relevant.

**Comment by jskeet** [comment]
Closing this now as we've just merged, with Ayyam-i-Ha at the end of month 18, and agreement that a separate library could exist to give a more detailed representation.
