### ISSUE TITLE
Create a single version history?

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#707]
Currently we have one version history per version, in the user guide.

Now we have a bit more control over the web site, perhaps there should only be *one* version history? That way it would be a lot easier to keep up to date - and in particular, we wouldn't *necessarily* have to sort out the 2.0 changes completely before shipping 2.0.

We could probably make it a top-level-banner option (like "More info", which I note is currently a broken link when you're not in the root directory - will fix that) - and we could just put the real markdown file in the "unstable" user guide but only there, or maybe in the developer guide.

**Comment by malcolmr** [comment]
(Also I note that we haven't been updating this for TZDB releases either, similar to #704.)

Yes, this makes sense to me. The only reason historically that version history was in the individual versions' user guides is because we shipped the documentation. Now that we're no longer doing that, it doesn't really make so much sense.

(Not sure whether that version history should be in `/developer/`, maybe just on the web site as a top-level item?)

**Comment by jskeet** [comment]
Yup. I just need to work out the best way of serving it, really (while still keeping it in Markdown, which I really want) - and then remove it from the old versions. Will have a think about that over the weekend.

**Comment by jskeet** [comment]
Fixed by #709.
