### ISSUE TITLE
Indicator if 'time' was provided

### ISSUE THREAD

**Issue by ozonni** [nodatime/nodatime#810]
I'm not sure that this is an issue, but i would like to know your opinion. 
As a request parameter client can specify date-time in iso 8601 format which could 

yyyy-MM-dd
yyyy-MM-ddTHH:mm:ss
yyyy-MM-ddTHH:mm:ssZ
yyyy-MM-ddTHH:mm:ss±hh:mm

If time is not set then DateTime object will have default value 00:00:00, and then it's hard to understand if client set it explicitly to midnight or it wasn't specified at all. Is there a way to get this somehow?

**Comment by jskeet** [comment]
There's nothing in Noda Time to support this directly. It sounds like you'd want something like:

```csharp
public struct LocalDateOptionalTime
{
    public LocalDate Date { get; }
    public LocalTime? Time { get; }
    // Construction etc
}
```

I don't anticipate putting that into Noda Time unless it turns out to be a common use case, but you should be able to do that reasonably easily yourself.

Note that the third and fourth values are more like `OffsetDateTime` and `LocalDateTime`. Another option would be a disjoint union of `LocalDate`, `LocalDateTime` and `OffsetDateTime`.

**Comment by ozonni** [comment]
Yes, this is an option. But it this case i need to implement custom JsonConverter to deserialize from string to complex type.

**Comment by jskeet** [comment]
Well yes - you've got what I'd consider to be a pretty unusual situation, so it makes sense that you'll need to write your own JSON converter to handle it. Unless we get significant demand for this, I wouldn't expect to handle this in Noda Time itself.

**Comment by jskeet** [comment]
I'm going to close this for now, as I believe it's a sufficiently unusual use case.
