### ISSUE TITLE
Missing Time Zone Info

### ISSUE THREAD

**Issue by SoftwareGuy88** [nodatime/nodatime#827]
I have noticed that you are missing a couple entries in the database file. I have found where they should go in the WindowsZone-31.xml file. I have added them and attached the file as a txt file. I am not sure if i can just do a pull request with the update or not but i just wanted to make sure that you were aware. Otherwise you have a great product. 

Line 98   -Need to add "America/Indiana/Indianapolis"

Need to add a new time zone entries under the "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi" section.
   --Asia/Kolkata

Update FIle.
[windowsZones-31.txt](https://github.com/nodatime/nodatime/files/1017147/windowsZones-31.txt)

**Comment by jskeet** [comment]
The file was extracted from CLDR 31.0 - I've just checked, and CLDR 31.0.1 is exactly the same.

What makes you think the entries are "missing"? I'm not going to start changing the files that are directly from CLDR. There's a facility in TzdbCompiler to use an extra file for any entries we want to include, but that's not the same as modifying the original CLDR data.

**Comment by SoftwareGuy88** [comment]
Well those 2 Olson TimeZones that are passed in, don't return anything. I am pulling these Olson TimeZones right from the browser. So someone is missing, just not sure who need to add them in. I have put code checks in there for those to get me buy but not sure who else is needing those time zones converted and they are getting nothing back. So i just wanted to let you know about it.

**Comment by jskeet** [comment]
Yes, it's known that not every IANA time zone is represented in CLDR's Windows mapping. You'll always need some kind of fallback, as it's entirely possible that a time zone is added between CLDR releases, for example.

In the case of Asia/Kolkata, I think this may well be due to that now being the IANA zone ID, but Calcutta being the stable ID used by CLDR.

In the case of America/Indiana/Indianapolis, there's a link from America/Indianapolis to America/Indiana/Indianapolis in IANA, and America/Indianapolis is in CLDR as "US Eastern Standard Time" - not "Central Standard Time" as per your patch.

It sounds like possibly the way forward is to make it easy to check whether there's an alias name in CLDR, so you could look up "Asia/Kolkata", Noda Time would know that Asia/Calcutta is an alias for that, and that it exists in CLDR, and return you the right result. No data changes would be need.

@mj1856 any thoughts around this?

**Comment by SoftwareGuy88** [comment]
Yeah that one was suppose to be Eastern Standard Time. I didn't catch that when i was typing that out.  So i will have to go back through the documentation of that and put the alas in there. I didn't know that was a possibility. I will check that out. Thanks for clearing that out. I will let you know if there are any other issues that come up.

**Comment by jskeet** [comment]
Reopening as a mutated feature request for the aliases to be included somehow, if @mj1856 (who knows more about the details of this) thinks it's a good idea.

**Comment by mj1856** [comment]
So, if you look through what I was originally doing with NodaTime [in this StackOverflow answer](https://stackoverflow.com/a/17348822/634824) you'll see that there's a lot of resolving of canonical entries.  Keep in mind that CLDR and IANA have different rules for what is "canonical".

If one is purely referencing CLDR, then to convert IANA to Windows for the example given:

- First look in [/common/bcp47/timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml) for the line containing `America/Indiana/Indianapolis`:

    ```xml
    <type name="usind" description="Indianapolis, United States" alias="America/Indianapolis America/Fort_Wayne America/Indiana/Indianapolis US/East-Indiana"/>
    ```
- Take the *first* entry in the alias string, which is `America/Indianapolis` 
- Look in [/common/supplemental/windowsZones.xml](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) for the line(s) with that entry:

    ```xml
     <!--  (UTC-05:00) Indiana (East)  -->
    <mapZone other="US Eastern Standard Time" territory="001" type="America/Indianapolis"/>
    <mapZone other="US Eastern Standard Time" territory="US" type="America/Indianapolis America/Indiana/Marengo America/Indiana/Vevay"/>
    ```
- Take the Windows ID from the `other` attribute.

There's no need to follow IANA `Link` entries when going in this direction.

The other direction is roughly the reverse, except you have to pick the `territory` entry you're interested in, and then check the IANA `Link` entries *instead of* the CLDR `/common/bcp47/timezone.xml` data.   Also, if you want UTC/UCT/GMT forms to map to a single entry, then you have to handle that yourself.

I do all this in the [TimeZoneNames](https://github.com/mj1856/TimeZoneNames) library, BTW.

So my understanding is that Noda Time has the CLDR data, but doesn't currently walk the aliases/links for canonicalization.  Is that what we're talking about adding?

**Comment by mj1856** [comment]
BTW, the data file should certainly not be altered.  If this is going to be handled in NodaTime, then we should pull in the `timezone.xml` file as a separate resource.

**Comment by jskeet** [comment]
@mj1856: Yes, we're talking about walking through the aliases in IANA data.

We don't *currently* have the CLDR `timezone.xml` data in Noda Time - only `windowsZones.xml`. We could introduce `timezone.xml` if we wanted to, of course - the NZD file format is deliberately extensible.

**Comment by jskeet** [comment]
Closing as I don't think we're actually going to do this. (The last comment being nearly 5 years ago suggests it's not a big issue.)
