### ISSUE TITLE
TFS Build Error

### ISSUE THREAD

**Issue by LCotts** [nodatime/nodatime#972]
Hi,

Just upgraded to the 2.2 package and upon check in our build server is complaining with the following:

##[error]Indexed source information could not be retrieved from '{pathtopdbfolder}\NodaTime.pdb'. Symbol indexes could not be retrieved

The build works but it shows as Partially Succeeded.

We are running TFS v 15.117.26714.0 and the target framework on the project using this package is 4.5.2

**Comment by jskeet** [comment]
I don't know anything about TFS, but looking at [similar](https://github.com/moq/moq4/issues/428) [issues](https://github.com/Microsoft/vsts-tasks/issues/4567) I think this is a matter of TFS not understanding portable PDBs. I'd rather not switch away from Portable PDBs at this point, particularly as I believe more support for them is being added in other areas.

Looking at [this request](https://developercommunity.visualstudio.com/content/problem/33776/indexed-source-information-could-not-be-retrieved-1.html) it looks like it'll be fixed in TFS 2018. Until then, I'd suggest investigating whether you could turn off source indexing for Noda Time in TFS.

**Comment by jskeet** [comment]
I'm going to close this as wontfix, not because I'm not sympathetic to your plight, but because I believe the downsides of moving away from Portable PDBs are bigger than the upsides.
